// config.bin - 11:42:26 05/22/17, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Vehicles_Wrecks {
		units[] = {"Land_bmp2_wrecked", "Land_BRDM2_wrecked", "Land_bvp1T", "Land_datsun01T", "Land_datsun01T_spodok", "Land_datsun02T", "Land_hiluxT", "Land_HMMWV_wrecked", "Land_Mi8_Crashed", "Land_UH1Y_Wreck", "Land_Skodovka_wrecked", "Land_T72_Wrecked", "Land_t72_wrecked_turret", "Land_uaz_wrecked", "Land_ural_wrecked", "Land_Ikarus_Dayz", "Land_Ikarus_ground_Dayz", "Land_Lada_DayZ", "Land_Lada_ground_DayZ", "Land_S1023_ground_DayZ", "Land_s1203_DayZ", "Land_Volha_DayZ", "Land_Volha_ground_DayZ"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Wreck_Base : HouseNoDestruct {
		accuracy = 0.3;	// accuracy needed to recognize type of this target
		cost = 10000;
	};
	
	class Land_bmp2_wrecked : Wreck_Base {
		scope = public;
		displayName = $STR_DN_BMP2WRECK;
		model = "\DZ\vehicles\wrecks\arma2\bmp2_wrecked.p3d";
	};
	
	class Land_BRDM2_wrecked : Wreck_Base {
		scope = public;
		displayName = $STR_DN_BRDMWRECK;
		model = "\DZ\vehicles\wrecks\arma2\BRDM2_wrecked.p3d";
	};
	
	class Land_bvp1T : Wreck_Base {
		scope = public;
		displayName = "bvp1T";
		model = "\DZ\vehicles\wrecks\arma2\bvp1T.p3d";
	};
	
	class Land_datsun01T : Wreck_Base {
		scope = public;
		displayName = "datsun01T";
		model = "\DZ\vehicles\wrecks\arma2\datsun01T.p3d";
	};
	
	class Land_datsun01T_spodok : Wreck_Base {
		scope = public;
		displayName = $STR_DN_DATSUN01WRECK;
		model = "\DZ\vehicles\wrecks\arma2\datsun01T_spodok.p3d";
	};
	
	class Land_datsun02T : Wreck_Base {
		scope = public;
		displayName = $STR_DN_DATSUN02WRECK;
		model = "\DZ\vehicles\wrecks\arma2\datsun02T.p3d";
	};
	
	class Land_hiluxT : Wreck_Base {
		scope = public;
		displayName = $STR_DN_HILUXWRECK;
		model = "\DZ\vehicles\wrecks\arma2\hiluxT.p3d";
	};
	
	class Land_HMMWV_wrecked : Wreck_Base {
		scope = public;
		displayName = $STR_DN_JEEPWRECK1;
		model = "\DZ\vehicles\wrecks\arma2\HMMWV_wrecked.p3d";
	};
	
	class Land_Skodovka_wrecked : Wreck_Base {
		scope = public;
		displayName = $STR_DN_SKODAWRECK;
		model = "\DZ\vehicles\wrecks\arma2\Skodovka_wrecked.p3d";
	};
	
	class Land_T72_Wrecked : Wreck_Base {
		scope = public;
		displayName = $STR_DN_T72WRECK;
		model = "\DZ\vehicles\wrecks\arma2\T72_Wrecked.p3d";
	};
	
	class Land_t72_wrecked_turret : Wreck_Base {
		scope = public;
		displayName = "$STR_DN_T72WRECK_Turret";
		model = "\DZ\vehicles\wrecks\arma2\t72_wrecked_turret.p3d";
	};
	
	class Land_uaz_wrecked : Wreck_Base {
		scope = public;
		displayName = $STR_DN_UAZWRECK;
		model = "\DZ\vehicles\wrecks\arma2\uaz_wrecked.p3d";
	};
	
	class Land_ural_wrecked : Wreck_Base {
		scope = public;
		displayName = $STR_DN_URALWRECK;
		model = "\DZ\vehicles\wrecks\arma2\ural_wrecked.p3d";
	};
	
	class Land_Ikarus_Dayz : Wreck_Base {
		scope = public;
		displayName = "Ikarus_Dayz";
		model = "\DZ\vehicles\wrecks\Ikarus\Ikarus_Dayz.p3d";
	};
	
	class Land_Ikarus_ground_Dayz : Wreck_Base {
		scope = public;
		displayName = "Ikarus_ground_Dayz";
		model = "\DZ\vehicles\wrecks\Ikarus\Ikarus_ground_Dayz.p3d";
	};
	
	class Land_Lada_DayZ : Wreck_Base {
		scope = public;
		displayName = "Lada_DayZ";
		model = "\DZ\vehicles\wrecks\Lada\Lada_DayZ.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors2 {
				displayName = "door 2";
				component = "Doors2";
				soundPos = "doors2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors4 {
				displayName = "door 4";
				component = "Doors4";
				soundPos = "doors4_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors5 {
				displayName = "door 5";
				component = "Doors5";
				soundPos = "doors5_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Lada_red_DayZ : Land_Lada_DayZ {
		model = "\DZ\vehicles\wrecks\Lada\Lada_red_DayZ.p3d";
	};
	
	class Land_Lada_ground_DayZ : Wreck_Base {
		scope = public;
		displayName = "Lada_ground_DayZ";
		model = "\DZ\vehicles\wrecks\Lada\Lada_ground_DayZ.p3d";
	};
	
	class Land_S1023_ground_DayZ : Wreck_Base {
		scope = public;
		displayName = "S1023_ground_DayZ";
		model = "\DZ\vehicles\wrecks\s1203\S1023_ground_DayZ.p3d";
	};
	
	class Land_s1203_DayZ : Wreck_Base {
		scope = public;
		displayName = "s1203_DayZ";
		model = "\DZ\vehicles\wrecks\s1203\s1203_DayZ.p3d";
		
		class Doors {
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_s1203_baige_DayZ : Land_s1203_DayZ {
		model = "\DZ\vehicles\wrecks\s1203\s1203_baige_DayZ.p3d";
	};
	
	class Land_Volha_DayZ : Wreck_Base {
		scope = public;
		displayName = "Volha_DayZ";
		model = "\DZ\vehicles\wrecks\Volha\Volha_DayZ.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors2 {
				displayName = "door 2";
				component = "Doors2";
				soundPos = "doors2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors4 {
				displayName = "door 4";
				component = "Doors4";
				soundPos = "doors4_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors5 {
				displayName = "door 5";
				component = "Doors5";
				soundPos = "doors5_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Volha_grey_DayZ : Land_Volha_DayZ {
		model = "\DZ\vehicles\wrecks\Volha\Volha_grey_DayZ.p3d";
	};
	
	class Land_Volha_ground_DayZ : Wreck_Base {
		scope = public;
		displayName = "Volha_ground_DayZ";
		model = "\DZ\vehicles\wrecks\Volha\Volha_ground_DayZ.p3d";
	};
	
	class Land_Volha_police_DayZ : Land_Volha_DayZ {
		storageCategory = 6;
		model = "\DZ\vehicles\wrecks\Volha\Volha_police_DayZ.p3d";
	};
	
	class Land_Mi8_Crashed : Wreck_Base {
		scope = public;
		storageCategory = 6;
		displayName = $STR_DN_MI8WRECK;
		model = "\DZ\vehicles\wrecks\arma2\Mi8_Crashed.p3d";
	};
	
	class Land_UH1Y_Wreck : Wreck_Base {
		scope = public;
		storageCategory = 6;
		model = "\DZ\vehicles\wrecks\UH1Y\UH1Y_Wreck.p3d";
		
		class EventHandlers {
			Init = "(_this select 0) call effect_createWreckSmoke;";
		};
	};
	
	class Land_V3S_wreck : Wreck_Base {
		scope = public;
		displayName = "V3S wreck";
		model = "DZ\vehicles\wrecks\V3S_wreck\V3S_wreck.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors2 {
				displayName = "door 2";
				component = "Doors2";
				soundPos = "doors2_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors5 {
				displayName = "door 5";
				component = "Doors5";
				soundPos = "doors5_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
};
