// config.bin - 12:08:04 05/22/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Castle {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class Land_A_Castle_Bastion : House {
		model = "\dz\structures\Castle\A_Castle_Bastion";
		featureSize = 12;
	};
	
	class Land_A_Castle_Gate : House {
		model = "\dz\structures\Castle\A_Castle_Gate";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall1_20 : House {
		model = "\dz\structures\Castle\A_Castle_Wall1_20";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall1_20_Turn : House {
		model = "\dz\structures\Castle\A_Castle_Wall1_20_Turn";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall1_Corner : House {
		model = "\dz\structures\Castle\A_Castle_Wall1_Corner";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall1_End : House {
		model = "\dz\structures\Castle\A_Castle_Wall1_End";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall1_End_2 : House {
		model = "\dz\structures\Castle\A_Castle_Wall1_End_2";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall2_30 : House {
		model = "\dz\structures\Castle\A_Castle_Wall2_30";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall2_Corner : House {
		model = "\dz\structures\Castle\A_Castle_Wall2_Corner";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall2_End : House {
		model = "\dz\structures\Castle\A_Castle_Wall2_End";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall2_End_2 : House {
		model = "\dz\structures\Castle\A_Castle_Wall2_End_2";
		featureSize = 12;
	};
	
	class Land_A_Castle_WallS_10 : House {
		model = "\dz\structures\Castle\A_Castle_WallS_10";
		featureSize = 12;
	};
	
	class Land_A_Castle_WallS_5_D : House {
		model = "\dz\structures\Castle\A_Castle_WallS_5_D";
		featureSize = 12;
	};
	
	class Land_A_Castle_WallS_End : House {
		model = "\dz\structures\Castle\A_Castle_WallS_End";
		featureSize = 12;
	};
	
	class Land_A_Castle_Stairs_A : House {
		model = "\dz\structures\Castle\A_Castle_Stairs_A";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall1_Corner_2 : House {
		model = "\dz\structures\Castle\A_Castle_Wall1_Corner_2";
		featureSize = 12;
	};
	
	class Land_A_Castle_Wall2_Corner_2 : House {
		model = "\dz\structures\Castle\A_Castle_Wall2_Corner_2";
		featureSize = 12;
	};
	
	class Land_A_Castle_Bergfrit : House {
		model = "\dz\structures\Castle\A_Castle_Bergfrit.p3d";
		featureSize = 30;
	};
	
	class Land_A_Castle_Donjon : House {
		model = "\dz\structures\Castle\A_Castle_Donjon.p3d";
		featureSize = 20;
	};
};
