// config.bin - 12:12:22 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define private		0
#define protected		1
#define public		2

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Pond {
		units[] = {"PondTest"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgSurfaces {
	class Default;	// External class reference
	
	class Freshwater : Default {
		access = ReadOnly;
		files = "watersurface*";
		rough = 0;
		dust = 0;
		soundEnviron = "water";
		friction = 0.9;
		restitution = 0;
		isWater = 1;
		character = "Empty";
		impact = "default_Mat";
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class PondTest : House {
		scope = public;
		displayName = "Pond";
		model = "\dz\structures\pond\pondtest.p3d";
	};
};
