// config.bin - 12:07:50 05/22/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Barn_W {
		units[] = {"Land_Barn_W_01", "Land_Barn_W_02"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class Land_Barn_W_01 : House {
		armor = 600;
		model = "\dz\structures\Barn_W\Barn_W_01.p3d";
		
		class HitPoints {
			class Hit1 {
				armor = 0.15;
				material = -1;
				name = "dam 1";
				visual = "damT1";
				passThrough = false;
				convexComponent = "dam 1";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
			
			class Hit2 {
				armor = 0.15;
				material = -1;
				name = "dam 2";
				visual = "damT2";
				passThrough = false;
				convexComponent = "dam 2";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
			
			class Hit3 {
				armor = 0.15;
				material = -1;
				name = "dam 3";
				visual = "damT3";
				passThrough = false;
				convexComponent = "dam 3";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
			
			class Hit4 {
				armor = 0.15;
				material = -1;
				name = "dam 4";
				visual = "damT4";
				passThrough = false;
				convexComponent = "dam 4";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
			
			class Hit5 {
				armor = 0.15;
				material = -1;
				name = "dam 5";
				visual = "damT5";
				passThrough = false;
				convexComponent = "dam 5";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
			
			class Hit6 {
				armor = 0.15;
				material = -1;
				name = "dam 6";
				visual = "damT6";
				passThrough = false;
				convexComponent = "dam 6";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
			
			class Hit7 {
				armor = 3;
				material = -1;
				name = "dam 7";
				visual = "damT7";
				passThrough = false;
				convexComponent = "dam 7";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
		};
		replaceDamagedHitpoints[] = {"Hit1", "Hit2", "Hit3", "Hit4", "Hit5", "Hit6", "Hit7"};
	};
	
	class Land_Barn_W_02 : Land_Barn_W_01 {
		armor = 400;
		model = "\dz\structures\Barn_W\Barn_W_02.p3d";
		
		class Damage {
			tex[] = {};
			mat[] = {};
		};
	};
};
