// config.bin - 11:58:01 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_Shed_small {
		units[] = {"Land_Shed_W01", "Land_Shed_W02", "Land_Shed_W03", "Land_Shed_M01", "Land_Shed_M02", "Land_Shed_M03"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Shed_W01 : HouseNoDestruct {
		armor = 30;
		model = "dz\buildings2\Shed_small\Shed_W01.p3d";
	};
	
	class Land_Shed_W02 : Land_Shed_W01 {
		model = "dz\buildings2\Shed_small\Shed_W02.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodNolatchOpen";
				soundClose = "doorWoodNolatchClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Shed_W03 : Land_Shed_W01 {
		model = "dz\buildings2\Shed_small\Shed_W03.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodNolatchOpen";
				soundClose = "doorWoodNolatchClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Shed_M01 : Land_Shed_W01 {
		model = "dz\buildings2\Shed_small\Shed_M01.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Shed_M02 : Land_Shed_W01 {
		model = "dz\buildings2\Shed_small\Shed_M02.p3d";
	};
	
	class Land_Shed_M03 : Land_Shed_W01 {
		model = "dz\buildings2\Shed_small\Shed_M03.p3d";
	};
};
