// config.bin - 12:10:19 05/22/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_House_Village_pub {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseWithFireplace;	// External class reference
	
	class Land_Village_pub : HouseWithFireplace {
		model = "DZ\structures\House\Village_pub\Village_pub.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 1;
				armor = 0.2;
				soundOpen = "doorWoodFrontOpen";
				soundClose = "doorWoodFrontClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors2 {
				displayName = "door 2";
				component = "Doors2";
				soundPos = "doors2_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorWoodFrontOpen";
				soundClose = "doorWoodFrontClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.7;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors4 {
				displayName = "door 4";
				component = "Doors4";
				soundPos = "doors4_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin {
				displayName = "door Twin";
				component = "DoorsTwin";
				soundPos = "doorsTwin_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
		
		class UserActions {
			class PlaceFireplace_bottom {
				displayNameDefault = "Place fireplace";
				displayName = "Place fireplace";
				onlyForPlayer = 0;
				condition = "[9, _person, [this, 'fireplace_slot1']] call fireplace_action_condition";
				statement = "[9, _person, [this, 'fireplace_point1', 'fireplace_smoke1','fireplace_slot1']] call fireplace_manageActions";
				component = "fireplace_action1";
			};
			
			class PlaceFireplace_top {
				displayNameDefault = "Place fireplace";
				displayName = "Place fireplace";
				onlyForPlayer = 0;
				condition = "[9, _person, [this, 'fireplace_slot2']] call fireplace_action_condition";
				statement = "[9, _person, [this, 'fireplace_point2', 'fireplace_smoke2', 'fireplace_slot2']] call fireplace_manageActions";
				component = "fireplace_action2";
			};
		};
	};
};
