// config.bin - 11:59:03 05/22/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_Ind_CementWorks_Ind_Mlyn {
		units[] = {"Land_Ind_Mlyn_01", "Land_Ind_Mlyn_02", "Land_Ind_Mlyn_03", "Land_Ind_Mlyn_04"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Ind_Mlyn_01 : HouseNoDestruct {
		model = "dz\buildings2\Ind_CementWorks\Ind_Mlyn\Ind_Mlyn_01.p3d";
		armor = 20000;
		featureSize = 40;
	};
	
	class Land_Ind_Mlyn_02 : HouseNoDestruct {
		model = "dz\buildings2\Ind_CementWorks\Ind_Mlyn\Ind_Mlyn_02.p3d";
		armor = 20000;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Ind_Mlyn_03 : HouseNoDestruct {
		model = "dz\buildings2\Ind_CementWorks\Ind_Mlyn\Ind_Mlyn_03.p3d";
		ladders[] = {{"start1", "end1"}, {"start2", "end2"}, {"start3", "end3"}, {"start4", "end4"}};
		armor = 20000;
		
		class Doors {
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Ind_Mlyn_04 : HouseNoDestruct {
		model = "dz\buildings2\Ind_CementWorks\Ind_Mlyn\Ind_Mlyn_04.p3d";
		armor = 20000;
	};
	
	class Land_Ind_Mlyn_D1 : HouseNoDestruct {
		model = "dz\buildings2\Ind_CementWorks\Ind_Mlyn\Ind_Mlyn_D1.p3d";
		armor = 20000;
	};
	
	class Land_Ind_Mlyn_D2 : HouseNoDestruct {
		model = "dz\buildings2\Ind_CementWorks\Ind_Mlyn\Ind_Mlyn_D2.p3d";
		armor = 20000;
	};
};
