// config.bin - 20:56:38 06/19/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_Ind_Garage01 {
		units[] = {"Land_Ind_Garage01"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Ind_Garage01 : HouseNoDestruct {
		animated = true;
		model = "dz\buildings2\Ind_Garage01\Ind_Garage01.p3d";
		scope = public;
		displayName = "Garage 1a";
		editorCategory = "DayZ";
		editorSubcategory = "DayZ_Buildings";
		
		class AnimationSources {
			class doorstwin1 {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.5;
			};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "twin1_action";
				radius = 2;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doorstwin1') >= 0.5)";
				statement = "(this animateSource ['doorstwin1', 0])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doorstwin1') < 0.5)";
				statement = "(this animateSource ['doorstwin1', 1])";
			};
		};
	};
};
