// config.bin - 11:57:09 05/22/17, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings {
		units[] = {"Land_Hlidac_budka", "Land_Hangar_2", "Land_molo_drevo_bs", "Land_molo_drevo_end", "Land_plot_zed_drevo1_branka", "Land_kulna", "Land_pumpa", "Land_vez", "Land_Vysilac_FM", "Land_telek1", "Land_Stoplight02", "Land_NavigLight", "Land_runway_edgelight", "Land_Runway_PAPI", "Land_Runway_PAPI_2", "Land_Runway_PAPI_3", "Land_Runway_PAPI_4", "Land_brana02nodoor", "Land_budova1", "Land_budova2", "Land_hut06", "Land_repair_center", "Land_sara_hasic_zbroj", "Land_SS_hangar", "Land_stodola_old_open", "Land_stodola_open", "Land_podesta_1_cube", "Land_podesta_1_cube_long", "Land_podesta_1_mid", "Land_podesta_1_mid_cornl", "Land_podesta_1_stairs3", "Land_podesta_1_stairs4", "Land_podesta_s5", "Land_ChristmasTree"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgDestroy {
	class BuildingHit {
		sound[] = {};
	};
};

class CfgVehicles {
	class Land_VASICore;	// External class reference
	class Static;	// External class reference
	class HouseNoDestruct;	// External class reference
	
	class UndergroundStash : HouseNoDestruct {
		scope = public;
		displayName = "Underground stash";
		model = "\DZ\buildings\underground_stash.p3d";
	};
	
	class Land_pumpa : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\misc\pumpa";
		storeVariables[] = {"quantity", "modifiers", "liquidType"};
		synchronizedVariables[] = {"quantity", 1, "liquidType", 1};
		
		class AnimationSources {
			class Arm {
				source = "user";
				initPhase = 0;
				animPeriod = 0.8;
			};
		};
	};
	
	class Land_Pristresek_mensi : HouseNoDestruct {
		scope = public;
		displayName = "Military Shed";
		model = "\DZ\buildings\tents\Pristresek_mensi.p3d";
	};
	
	class Land_plot_zed_drevo1_branka : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\misc\plot_zed_drevo1_branka";
	};
	
	class Land_sara_hasic_zbroj : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\sara_hasic_zbroj";
	};
	
	class Land_SS_hangar : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\SS_hangar";
	};
	
	class Land_stodola_old_open : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\stodola_old_open";
	};
	
	class Land_stodola_open : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\stodola_open";
	};
	
	class Land_brana02nodoor : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\brana02nodoor";
	};
	
	class Land_molo_drevo_bs : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\molo_drevo_bs";
	};
	
	class Land_molo_drevo_end : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\molo_drevo_end";
	};
	
	class Land_kulna : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\kulna";
	};
	
	class Land_psi_bouda : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\psi_bouda";
	};
	
	class Land_trafostanica_velka_draty : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\trafostanica_velka_draty";
	};
	
	class Land_trafostanica_velka : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\trafostanica_velka";
	};
	
	class Land_hut06 : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\hut06";
	};
	
	class Land_repair_center : HouseNoDestruct {
		model = "dz\buildings\repair_center.p3d";
		animated = true;
		
		class Doors {
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin2 {
				displayName = "door Twin2";
				component = "DoorsTwin2";
				soundPos = "doorsTwin2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_podesta_1_cube : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\podesta_1_cube";
	};
	
	class Land_podesta_1_cube_long : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\podesta_1_cube_long";
	};
	
	class Land_podesta_1_mid : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\podesta_1_mid";
	};
	
	class Land_podesta_1_mid_cornl : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\podesta_1_mid_cornl";
	};
	
	class Land_podesta_1_stairs3 : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\podesta_1_stairs3";
	};
	
	class Land_podesta_1_stairs4 : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\podesta_1_stairs4";
	};
	
	class Land_podesta_s5 : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\podesta_s5";
	};
	
	class Land_Hangar_2 : HouseNoDestruct {
		displayName = $STR_DN_HANGAR2;
		model = "dz\buildings\hangar_2.p3d";
		armor = 2000;
		animated = true;
		
		class Doors {
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 3;
				initPhase = 0;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorMetalSlideOpen";
				soundClose = "doorMetalSlideClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors4 {
				displayName = "door 4";
				component = "Doors4";
				soundPos = "doors4_action";
				animPeriod = 3;
				initPhase = 0;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorMetalSlideOpen";
				soundClose = "doorMetalSlideClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Budova4_in : HouseNoDestruct {
		model = "dz\buildings\budova4_in.p3d";
		animated = true;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors2 {
				displayName = "door 2";
				component = "Doors2";
				soundPos = "doors2_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors4 {
				displayName = "door 4";
				component = "Doors4";
				soundPos = "doors4_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Garaz : HouseNoDestruct {
		model = "dz\buildings\garaz.p3d";
		animated = true;
		
		class Doors {
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin2 {
				displayName = "door Twin2";
				component = "DoorsTwin2";
				soundPos = "doorsTwin2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin3 {
				displayName = "door Twin3";
				component = "DoorsTwin3";
				soundPos = "doorsTwin3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_KBud : HouseNoDestruct {
		model = "dz\buildings\Misc\KBud.p3d";
		animated = true;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorWoodNolatchOpen";
				soundClose = "doorWoodNolatchClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Hlidac_budka : HouseNoDestruct {
		displayName = $STR_MISC_LINE_KEEPER_BOX;
		model = "dz\buildings\Hlidac_budka.p3d";
		armor = 200;
		mapSize = 2;
		animated = true;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodFrontOpen";
				soundClose = "doorWoodFrontClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_sara_domek_zluty : HouseNoDestruct {
		model = "dz\buildings\sara_domek_zluty.p3d";
		animated = true;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodFrontOpen";
				soundClose = "doorWoodFrontClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_posed : HouseNoDestruct {
		model = "dz\buildings\posed.p3d";
		ladders[] = {{"start", "end"}};
	};
	
	class Land_vez : HouseNoDestruct {
		model = "dz\buildings\vez.p3d";
		ladders[] = {{"start", "end"}};
	};
	
	class Land_Nasypka : HouseNoDestruct {
		model = "dz\buildings\Misc\Nasypka.p3d";
		ladders[] = {{"start", "end"}};
	};
	
	class Land_Tovarna2 : HouseNoDestruct {
		model = "dz\buildings\tovarna2.p3d";
		armor = 800;
		ladders[] = {{"start1", "end1"}, {"start3", "end3"}, {"start4", "end4"}, {"start5", "end5"}};
	};
	
	class Land_Vysilac_FM : HouseNoDestruct {
		displayName = $STR_DN_RADAR1;
		model = "dz\buildings\Vysilac_FM.p3d";
		ladders[] = {{"start", "end"}};
	};
	
	class Land_telek1 : HouseNoDestruct {
		displayName = $STR_DN_TELEK1;
		model = "dz\buildings\telek1.p3d";
		ladders[] = {{"start1", "end1"}, {"start2", "end2"}, {"start3", "end3"}};
	};
	
	class Land_komin : HouseNoDestruct {
		model = "dz\buildings\komin.p3d";
		armor = 300;
		ladders[] = {{"start", "end"}};
	};
	
	class Land_Stoplight02 : HouseNoDestruct {
		model = "dz\buildings\Misc\stoplight02.p3d";
	};
	
	class Land_NavigLight : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\Misc\NavigLight.p3d";
		armor = 50;
	};
	
	class Land_runway_edgelight : HouseNoDestruct {
		displayName = "";
		model = "dz\buildings\Misc\runway_edgelight.p3d";
		armor = 20;
	};
	
	class Land_plot_green_branka : HouseNoDestruct {
		model = "dz\buildings\misc\plot_green_branka.p3d";
		animated = true;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.8;
				armor = 0.2;
				soundOpen = "doorFenceMetalOpen";
				soundClose = "doorFenceMetalClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_plot_green_vrata : HouseNoDestruct {
		model = "dz\buildings\misc\plot_green_vrata.p3d";
		animated = true;
		
		class Doors {
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorFenceMetalTwinOpen";
				soundClose = "doorFenceMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_plot_green_vrat_l : HouseNoDestruct {
		model = "DZ\buildings\misc\plot_green_vrat_l.p3d";
		animated = true;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorFenceMetalOpen";
				soundClose = "doorFenceMetalClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_plot_green_brank_o : Land_plot_green_vrat_l {
		model = "DZ\buildings\misc\plot_green_brank_o.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorFenceMetalOpen";
				soundClose = "doorFenceMetalClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_plot_green_vrat_o : HouseNoDestruct {
		model = "DZ\buildings\misc\plot_green_vrat_o.p3d";
		animated = true;
		
		class Doors {
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.1;
				armor = 0.2;
				soundOpen = "doorFenceMetalTwinOpen";
				soundClose = "doorFenceMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_pletivo_wired_branaL_civil : HouseNoDestruct {
		model = "DZ\buildings\misc\pletivo_wired_branaL_civil.p3d";
		animated = true;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorFenceMetalOpen";
				soundClose = "doorFenceMetalClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_plot_rust_branka : Land_plot_green_branka {
		model = "dz\buildings\misc\plot_rust_branka.p3d";
	};
	
	class Land_ChristmasTree : Land_plot_green_branka {
		model = "dz\plants2\tree\t_picea2s_christmas.p3d";
	};
	
	class Land_plot_rust_vrata : Land_plot_green_vrata {
		model = "dz\buildings\misc\plot_rust_vrata.p3d";
	};
	
	class Land_plot_green_vrat_r : Land_plot_green_vrat_l {
		model = "DZ\buildings\misc\plot_green_vrat_r.p3d";
	};
	
	class Land_plot_rust_vrat_l : Land_plot_green_vrat_l {
		model = "DZ\buildings\misc\plot_rust_vrat_l.p3d";
	};
	
	class Land_plot_rust_vrat_r : Land_plot_green_vrat_l {
		model = "DZ\buildings\misc\plot_rust_vrat_r.p3d";
	};
	
	class Land_plot_rust_brank_o : Land_plot_green_brank_o {
		model = "DZ\buildings\misc\plot_rust_brank_o.p3d";
	};
	
	class Land_plot_rust_vrat_o : Land_plot_green_vrat_o {
		model = "DZ\buildings\misc\plot_rust_vrat_o.p3d";
	};
	
	class Land_pletivo_wired_branaP : Land_pletivo_wired_branaL_civil {
		model = "DZ\buildings\misc\pletivo_wired_branaP.p3d";
	};
	
	class StreetLampOff : HouseNoDestruct {};
	
	class Land_Camp : HouseNoDestruct {
		displayName = $STR_DN_TENT;
		model = "dz\buildings\Tents\Camp.p3d";
		icon = "dz\buildings\Icons\i_Camp_CA.paa";
		mapSize = 6.4;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		cost = 20;
	};
	
	class Land_CampEast : Land_Camp {
		displayName = $STR_DN_CAMPEAST;
		model = "dz\buildings\Tents\CampEast.p3d";
		icon = "dz\buildings\Icons\i_CampEast_CA.paa";
	};
	
	class Land_ACamp : Land_Camp {
		displayName = $STR_DN_ACAMP;
		model = "dz\buildings\Tents\ACamp.p3d";
		icon = "dz\buildings\Icons\i_ACamp_CA.paa";
		mapSize = 2.6;
	};
	
	class Land_Mash : Land_Camp {
		displayName = $STR_DN_MASH;
		model = "dz\buildings\Tents\mash.p3d";
		icon = "dz\buildings\Icons\i_MASH_CA.paa";
		accuracy = 0.3;	// accuracy needed to recognize type of this target
		attendant = true;
		mapSize = 6.4;
		supplyRadius = 9.3;
	};
};

class CfgNonAIVehicles {
	class StreetLamp {
		colorDiffuse[] = {0.9, 0.8, 0.6};
		colorAmbient[] = {0.02, 0.02, 0.02};
		radius = 37.5;
	};
};

class CfgSFX {
	class Church {
		smallBell[] = {"dz\buildings\Sound\bell1", 0.1, 1};
		largeBell[] = {"dz\buildings\Sound\bell2", 0.316228, 1};
	};
};
