// config.bin - 12:12:28 05/22/17, generated in 0.08 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Prison_complex {
		units[] = {"Prison_castle_INT", "Prison_castle_EXT"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Prison_MainCastle_EXT : HouseNoDestruct {
		model = "DZ\structures\Prison_complex\Prison_MainCastle_EXT.p3d";
		featureSize = 50;
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors2 {
				displayName = "door 2";
				component = "Doors2";
				soundPos = "doors2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors4 {
				displayName = "door 4";
				component = "Doors4";
				soundPos = "doors4_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors5 {
				displayName = "door 5";
				component = "Doors5";
				soundPos = "doors5_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors6 {
				displayName = "door 6";
				component = "Doors6";
				soundPos = "doors6_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors7 {
				displayName = "door 7";
				component = "Doors7";
				soundPos = "doors7_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors8 {
				displayName = "door 8";
				component = "Doors8";
				soundPos = "doors8_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors9 {
				displayName = "door 9";
				component = "Doors9";
				soundPos = "doors9_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors10 {
				displayName = "door 10";
				component = "Doors10";
				soundPos = "doors10_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors11 {
				displayName = "door 11";
				component = "Doors11";
				soundPos = "doors11_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors12 {
				displayName = "door 12";
				component = "Doors12";
				soundPos = "doors12_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors13 {
				displayName = "door 13";
				component = "Doors13";
				soundPos = "doors13_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors14 {
				displayName = "door 14";
				component = "Doors14";
				soundPos = "doors14_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors15 {
				displayName = "door 15";
				component = "Doors15";
				soundPos = "doors15_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors16 {
				displayName = "door 16";
				component = "Doors16";
				soundPos = "doors16_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors17 {
				displayName = "door 17";
				component = "Doors17";
				soundPos = "doors17_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors18 {
				displayName = "door 18";
				component = "Doors18";
				soundPos = "doors18_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors19 {
				displayName = "door 19";
				component = "Doors19";
				soundPos = "doors19_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors20 {
				displayName = "door 20";
				component = "Doors20";
				soundPos = "doors20_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors21 {
				displayName = "door 21";
				component = "Doors21";
				soundPos = "doors21_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors22 {
				displayName = "door 22";
				component = "Doors22";
				soundPos = "doors22_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors23 {
				displayName = "door 23";
				component = "Doors23";
				soundPos = "doors23_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors24 {
				displayName = "door 24";
				component = "Doors24";
				soundPos = "doors24_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors25 {
				displayName = "door 25";
				component = "Doors25";
				soundPos = "doors25_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors26 {
				displayName = "door 26";
				component = "Doors26";
				soundPos = "doors26_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors27 {
				displayName = "door 27";
				component = "Doors27";
				soundPos = "doors27_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors28 {
				displayName = "door 28";
				component = "Doors28";
				soundPos = "doors28_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors29 {
				displayName = "door 29";
				component = "Doors29";
				soundPos = "doors29_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors30 {
				displayName = "door 30";
				component = "Doors30";
				soundPos = "doors30_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors31 {
				displayName = "door 31";
				component = "Doors31";
				soundPos = "doors31_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors32 {
				displayName = "door 32";
				component = "Doors32";
				soundPos = "doors32_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors33 {
				displayName = "door 33";
				component = "Doors33";
				soundPos = "doors33_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors34 {
				displayName = "door 34";
				component = "Doors34";
				soundPos = "doors34_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors35 {
				displayName = "door 35";
				component = "Doors35";
				soundPos = "doors35_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors36 {
				displayName = "door 36";
				component = "Doors36";
				soundPos = "doors36_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors37 {
				displayName = "door 37";
				component = "Doors37";
				soundPos = "doors37_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors38 {
				displayName = "door 38";
				component = "Doors38";
				soundPos = "doors38_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors39 {
				displayName = "door 39";
				component = "Doors39";
				soundPos = "doors39_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors40 {
				displayName = "door 40";
				component = "Doors40";
				soundPos = "doors40_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors41 {
				displayName = "door 41";
				component = "Doors41";
				soundPos = "doors41_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors42 {
				displayName = "door 42";
				component = "Doors42";
				soundPos = "doors42_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors43 {
				displayName = "door 43";
				component = "Doors43";
				soundPos = "doors43_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors44 {
				displayName = "door 44";
				component = "Doors44";
				soundPos = "doors44_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors45 {
				displayName = "door 45";
				component = "Doors45";
				soundPos = "doors45_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors46 {
				displayName = "door 46";
				component = "Doors46";
				soundPos = "doors46_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors47 {
				displayName = "door 47";
				component = "Doors47";
				soundPos = "doors47_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors48 {
				displayName = "door 48";
				component = "Doors48";
				soundPos = "doors48_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors49 {
				displayName = "door 49";
				component = "Doors49";
				soundPos = "doors49_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors50 {
				displayName = "door 50";
				component = "Doors50";
				soundPos = "doors50_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors51 {
				displayName = "door 51";
				component = "Doors51";
				soundPos = "doors51_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors52 {
				displayName = "door 52";
				component = "Doors52";
				soundPos = "doors52_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors53 {
				displayName = "door 53";
				component = "Doors53";
				soundPos = "doors53_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors54 {
				displayName = "door 54";
				component = "Doors54";
				soundPos = "doors54_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors55 {
				displayName = "door 55";
				component = "Doors55";
				soundPos = "doors55_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors56 {
				displayName = "door 56";
				component = "Doors56";
				soundPos = "doors56_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorMetalBigOpen";
				soundClose = "doorMetalBigClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors57 {
				displayName = "door 57";
				component = "Doors57";
				soundPos = "doors57_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors58 {
				displayName = "door 58";
				component = "Doors58";
				soundPos = "doors58_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors59 {
				displayName = "door 59";
				component = "Doors59";
				soundPos = "doors59_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors60 {
				displayName = "door 60";
				component = "Doors60";
				soundPos = "doors60_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors61 {
				displayName = "door 61";
				component = "Doors61";
				soundPos = "doors61_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors62 {
				displayName = "door 62";
				component = "Doors62";
				soundPos = "doors62_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors63 {
				displayName = "door 63";
				component = "Doors63";
				soundPos = "doors63_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors64 {
				displayName = "door 64";
				component = "Doors64";
				soundPos = "doors64_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors65 {
				displayName = "door 65";
				component = "Doors65";
				soundPos = "doors65_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors66 {
				displayName = "door 66";
				component = "Doors66";
				soundPos = "doors66_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.35;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.6;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin2 {
				displayName = "door Twin2";
				component = "DoorsTwin2";
				soundPos = "doorsTwin2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin3 {
				displayName = "door Twin3";
				component = "DoorsTwin3";
				soundPos = "doorsTwin3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.4;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin4 {
				displayName = "door Twin4";
				component = "DoorsTwin4";
				soundPos = "doorsTwin4_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin5 {
				displayName = "door Twin5";
				component = "DoorsTwin5";
				soundPos = "doorsTwin5_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin6 {
				displayName = "door Twin6";
				component = "DoorsTwin6";
				soundPos = "doorsTwin6_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin7 {
				displayName = "door Twin7";
				component = "DoorsTwin7";
				soundPos = "doorsTwin7_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin8 {
				displayName = "door Twin8";
				component = "DoorsTwin8";
				soundPos = "doorsTwin8_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.4;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Prison_SideBuilding_EXT : HouseNoDestruct {
		model = "DZ\structures\Prison_complex\Prison_SideBuilding_EXT.p3d";
		featureSize = 50;
		
		class Doors {
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors4 {
				displayName = "door 4";
				component = "Doors4";
				soundPos = "doors4_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors11 {
				displayName = "door 11";
				component = "Doors11";
				soundPos = "doors11_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors12 {
				displayName = "door 12";
				component = "Doors12";
				soundPos = "doors12_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors19 {
				displayName = "door 19";
				component = "Doors19";
				soundPos = "doors19_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors20 {
				displayName = "door 20";
				component = "Doors20";
				soundPos = "doors20_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors21 {
				displayName = "door 21";
				component = "Doors21";
				soundPos = "doors21_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors22 {
				displayName = "door 22";
				component = "Doors22";
				soundPos = "doors22_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors23 {
				displayName = "door 23";
				component = "Doors23";
				soundPos = "doors23_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors24 {
				displayName = "door 24";
				component = "Doors24";
				soundPos = "doors24_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors25 {
				displayName = "door 25";
				component = "Doors25";
				soundPos = "doors25_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors26 {
				displayName = "door 26";
				component = "Doors26";
				soundPos = "doors26_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.6;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin2 {
				displayName = "door Twin2";
				component = "DoorsTwin2";
				soundPos = "doorsTwin2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin3 {
				displayName = "door Twin3";
				component = "DoorsTwin3";
				soundPos = "doorsTwin3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.4;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin4 {
				displayName = "door Twin4";
				component = "DoorsTwin4";
				soundPos = "doorsTwin4_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin5 {
				displayName = "door Twin5";
				component = "DoorsTwin5";
				soundPos = "doorsTwin5_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin6 {
				displayName = "door Twin6";
				component = "DoorsTwin6";
				soundPos = "doorsTwin6_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin7 {
				displayName = "door Twin7";
				component = "DoorsTwin7";
				soundPos = "doorsTwin7_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin8 {
				displayName = "door Twin8";
				component = "DoorsTwin8";
				soundPos = "doorsTwin8_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.4;
				armor = 0.2;
				soundOpen = "doorWoodTwinOpen";
				soundClose = "doorWoodTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin9 {
				displayName = "door Twin9";
				component = "DoorsTwin9";
				soundPos = "doorsTwin9_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.4;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Prison_LargeWall : HouseNoDestruct {
		armor = 20000;
		model = "DZ\structures\Prison_complex\Prison_LargeWall.p3d";
	};
};
