// config.bin - 12:00:38 05/22/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Misc {
		units[] = {"Fence", "FenceWood", "FenceWoodPalet"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};
class SmallFire;	// External class reference

class cfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_houpacka : HouseNoDestruct {
		displayName = $STR_DN_SWING;
		model = "\dz\misc\houpacka.p3d";
		icon = "\dz\data\data\Unknown_object.paa";
	};
	
	class Land_Piskoviste : HouseNoDestruct {
		displayName = $STR_DN_SANDPIT;
		model = "\dz\misc\piskoviste.p3d";
		icon = "\dz\data\data\Unknown_object.paa";
	};
	
	class Land_sekyraspalek : HouseNoDestruct {
		model = "\dz\misc\sekyraspalek.p3d";
	};
	
	class Land_jezekbeton : HouseNoDestruct {
		displayName = $STR_DN_HOUSE;
		model = "\dz\misc\jezekbeton.p3d";
		icon = "\dz\misc\data\icons\i_jez_CA.paa";
		armor = 800;
	};
	
	class Land_fuel_tank_small : HouseNoDestruct {
		model = "\dz\misc\fuel_tank_small.p3d";
		icon = "\dz\misc\data\icons\i_fuel_CA.paa";
		armor = 50;
		accuracy = 0.5;	// accuracy needed to recognize type of this target
	};
	
	class Land_Fuel_tank_big : Land_fuel_tank_small {
		displayName = $STR_DN_FUEL_STATION;
		model = "\dz\misc\Fuel_tank_big.p3d";
		icon = "\dz\misc\data\icons\i_fuel_CA.paa";
	};
	
	class Land_Fuel_tank_stairs : Land_fuel_tank_small {
		model = "\dz\misc\Fuel_tank_stairs.p3d";
		icon = "\dz\misc\data\icons\i_fuel_CA.paa";
		ladders[] = {{"start", "end"}};
	};
	
	class Land_water_tank : HouseNoDestruct {
		model = "\dz\misc\water_tank.p3d";
		icon = "\dz\data\data\Unknown_object.paa";
		ladders[] = {{"start", "end"}};
		armor = 500;
	};
	
	class Land_sloup_vn : HouseNoDestruct {
		model = "\dz\misc\sloup_vn.p3d";
		icon = "\dz\data\data\Unknown_object.paa";
		armor = 300;
	};
	
	class Land_sloup_vn_dratZ : HouseNoDestruct {
		model = "\dz\misc\sloup_vn_dratZ.p3d";
		icon = "\dz\data\data\Unknown_object.paa";
		armor = 20;
	};
	
	class Land_sloup_vn_drat : Land_sloup_vn_dratZ {
		model = "\dz\misc\sloup_vn_drat.p3d";
		icon = "\dz\data\data\Unknown_object.paa";
		armor = 20;
	};
	
	class Land_sloup_vn_drat_d : Land_sloup_vn_drat {
		model = "\dz\misc\sloup_vn_drat_d.p3d";
	};
	
	class Land_CampfireNew : HouseNoDestruct {
		scope = public;
		displayName = "Campfire DN";
		model = "\dz\misc\Campfire.p3d";
		icon = "\dz\data\data\Unknown_object.paa";
		simulation = "fire";
		cost = 0;
		
		class Effects : SmallFire {
			class Light1 {
				simulation = "light";
				type = "SmallFireLight";
			};
			
			class sound {
				simulation = "sound";
				type = "Fire";
			};
			
			class Fire1 {
				simulation = "particles";
				type = "SmallFire1";
			};
		};
	};
	
	class Land_Fort_EnvelopeSmall : HouseNoDestruct {
		displayName = $STR_DN_ENVELOPESMALL;
		model = "\dz\misc\Fort_EnvelopeSmall.p3d";
		mapSize = 2;
	};
	
	class Land_Fort_EnvelopeBig : HouseNoDestruct {
		displayName = $STR_DN_ENVELOPEBIG;
		model = "\dz\misc\Fort_EnvelopeBig.p3d";
		mapSize = 4;
	};
	
	class Land_seno_balik : HouseNoDestruct {
		model = "\dz\misc\seno_balik.p3d";
		armor = 100;
	};
	
	class Land_sunshade : HouseNoDestruct {
		model = "\dz\misc\Sunshade_F.p3d";
		armor = 100;
	};
	
	class Land_ladder : HouseNoDestruct {
		model = "\dz\misc\ladder.p3d";
		ladders[] = {{"start1", "end1"}};
		armor = 100;
	};
	
	class Land_ladder_half : HouseNoDestruct {
		model = "\dz\misc\ladder_half.p3d";
		ladders[] = {{"start1", "end1"}};
		armor = 100;
	};
};
