// config.bin - 11:41:00 05/22/17, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class DZ_UIFonts_CoreConfigOverwrite {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_UIFonts"};
	};
};
class RscText;	// External class reference
class RscActiveText;	// External class reference
class RscStructuredText;	// External class reference
class RscButton;	// External class reference
class RscStandardDisplay;	// External class reference

class RscPicture {
	font = "AmorSerifPro";
};

class CfgInGameUI {
	class HelicopterHUD {
		font = "AmorSerifPro";
	};
	
	class DefaultAction {
		fontNext = "AmorSerifPro";
	};
};

class RscXKeyShadow {
	class Attributes {
		font = "AmorSerifPro";
	};
};

class RscMapControl {
	font = "AmorSerifPro";
};

class RscDisplayMissionEditor {
	class Menu {
		font = "AmorSerifPro";
	};
};

class RscDisplayCapture {
	class Controls {
		class TimeLines {
			font = "AmorSerifPro";
		};
	};
};

class RscIGText : RscText {
	font = "AmorSerifPro";
};

class RscDisplayHintC {
	class controls {
		class continue : RscActiveText {
			font = "AmorSerifPro";
		};
	};
};

class RscDisplayHintCEx {
	class controls {
		class Title : RscText {
			font = "AmorSerifPro";
		};
		
		class continue : RscActiveText {
			font = "AmorSerifPro";
		};
	};
};

class RscInGameUI {
	class RscUnitInfo {
		class Background : RscText {
			font = "AmorSerifPro";
		};
		
		class Background2 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class RscUnitInfoSoldier : RscUnitInfo {
		class Background : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class RscUnitInfoTank : RscUnitInfo {
		class Background : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class RscHint {
		class Background : RscText {
			font = "AmorSerifPro";
		};
		
		class Hint : RscStructuredText {
			font = "AmorSerifPro";
		};
	};
	
	class RscTaskHint {
		class controlsBackground {
			class Background : RscText {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscTitles {
	class default;	// External class reference
	
	class DefPic : default {
		font = "AmorSerifPro";
	};
	
	class BIS {
		class WWW : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class LegalScreen {
		class CopText : RscText {
			font = "AmorSerifPro";
		};
		
		class InfoText : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Features1 {
		class Text1 : RscText {
			font = "AmorSerifPro";
		};
		
		class Text2 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class creditsbackBIS {
		class web : RscText {
			font = "AmorSerifPro";
		};
		
		class dev : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISleader : creditsbackBIS {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISprogram : creditsbackBIS {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISart : creditsbackBIS {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISdesign : creditsbackBIS {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISother1 : creditsbackBIS {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
		
		class work2 : RscText {
			font = "AmorSerifPro";
		};
		
		class name2 : RscText {
			font = "AmorSerifPro";
		};
		
		class work3 : RscText {
			font = "AmorSerifPro";
		};
		
		class name3 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISmusic : creditsbackBIS {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name2 : RscText {
			font = "AmorSerifPro";
		};
		
		class name3 : RscText {
			font = "AmorSerifPro";
		};
		
		class name4 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISsfx : creditsbackBIS {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
		
		class work2 : RscText {
			font = "AmorSerifPro";
		};
		
		class name2 : RscText {
			font = "AmorSerifPro";
		};
		
		class copy : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class BISthx : creditsbackBIS {
		class work2 : RscText {
			font = "AmorSerifPro";
		};
		
		class name2 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class creditsbackCM {
		class pub : RscText {
			font = "AmorSerifPro";
		};
		
		class web : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class CMProducer : creditsbackCM {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class CMdesign : creditsbackCM {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class CMQA : creditsbackCM {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class CMMrkev : creditsbackCM {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class CMVoice : creditsbackCM {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
		
		class work2 : RscText {
			font = "AmorSerifPro";
		};
		
		class name2 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class CMlocal : creditsbackCM {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
		
		class work2 : RscText {
			font = "AmorSerifPro";
		};
		
		class name2 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class CMlegal : creditsbackCM {
		class work1 : RscText {
			font = "AmorSerifPro";
		};
		
		class name1 : RscText {
			font = "AmorSerifPro";
		};
		
		class work2 : RscText {
			font = "AmorSerifPro";
		};
		
		class name2 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Endof {
		class copy : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class foto {
		class copy : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Endof2 {
		class copy : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class maintitles1 {
		class maintitles_01 : RscText {
			font = "AmorSerifPro";
		};
		
		class maintitles_02 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class maintitles2 {
		class maintitles_03 : RscText {
			font = "AmorSerifPro";
		};
		
		class maintitles_04 : RscText {
			font = "AmorSerifPro";
		};
		
		class maintitles_05 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class maintitles3 {
		class maintitles_06 : RscText {
			font = "AmorSerifPro";
		};
		
		class maintitles_07 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Demo1 {
		class Text : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Demo2 {
		class Text : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Demo3 {
		class Text : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Demo4 {
		class Text : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Demo5 {
		class Text : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Demo6 {
		class Text : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class Demo7 {
		class Text : RscText {
			font = "AmorSerifPro";
		};
		
		class Text1 : RscText {
			font = "AmorSerifPro";
		};
	};
	
	class UnlockMission {
		class Text : RscText {
			font = "AmorSerifPro";
		};
	};
};

class RscDisplayEditProfile {
	class controls {
		class ValueController : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayProfileFace {
	class controls {
		class TextFace : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayProfileController : RscStandardDisplay {
	class controls {
		class HeadlineL : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class HeadlineR : HeadlineL {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class AButton : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class LeftTrigger : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class RightTrigger : LeftTrigger {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class WhiteButton : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class BackButton : WhiteButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class LeftStickX : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class DStick : LeftStickX {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class RightStickX : LeftStickX {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayProfileControllerWheel : RscStandardDisplay {
	class controls {
		class HeadlineD : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class AButton : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class LeftTrigger : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class RightTrigger : LeftTrigger {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class WhiteButton : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class BackButton : WhiteButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class DStick : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayProfileControllerJoystick : RscStandardDisplay {
	class controls {
		class HeadlineL : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class HeadlineR : HeadlineL {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class AButton : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class YButton : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class LeftTrigger : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class RightTrigger : LeftTrigger {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class WhiteButton : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class BackButton : WhiteButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class LeftStickX : AButton {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class DStick : LeftStickX {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
		
		class RightStickX : LeftStickX {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayLive : RscStandardDisplay {
	class Controls {
		class QuickMatch : RscButton {
			font = "AmorSerifPro";
			
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayMPType : RscStandardDisplay {
	class Controls {
		class RankedMatch : RscButton {
			font = "AmorSerifPro";
			
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayQuickMatch : RscStandardDisplay {
	class Controls {
		class HostValue : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayPlayers : RscStandardDisplay {
	class Controls {
		class PlayerStatusText : RscText {
			font = "AmorSerifPro";
		};
		
		class PlayerStatusValue : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};

class RscDisplayStatisticsCurrent : RscStandardDisplay {
	class controls {
		class TotalValue : RscStructuredText {
			class Attributes {
				font = "AmorSerifPro";
			};
		};
	};
};
