// config.bin - 12:01:23 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Roads2_Dam {
		units[] = {"Land_Dam_Conc_20", "Land_Dam_ConcP_20", "Land_Dam_Barrier_40"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Roads2"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class Land_Dam_Conc_20 : House {
		scope = protected;
		model = "\dz\roads2\dam\dam_conc\dam_conc_20.p3d";
		destrType = "DestructBuilding";
		
		class DestructionEffects {};
	};
	
	class Land_Dam_ConcP_20 : Land_Dam_Conc_20 {
		model = "\dz\roads2\dam\dam_conc\dam_concP_20.p3d";
		ladders[] = {{"start", "end"}};
	};
	
	class Land_Dam_Barrier_40 : Land_Dam_Conc_20 {
		model = "\dz\roads2\dam\dam_barrier_40\dam_barrier_40.p3d";
	};
};
