// config.bin - 12:08:11 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class DZ_Structures_Furniture {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgNonAIVehicles {
	class ProxyAlmara_open {
		scope = public;
		model = "\DZ\structures\Furniture\Cases\almara\almara_open.p3d";
		autocenter = "false";
		reversed = "false";
		animated = "false";	// true = model is animated and cannot be assumed static
		shadow = "false";
		proxyDisplayName = "Wardrobe";
		simulation = "alwaysshow";
		
		class Cargo {
			itemsCargoSize[] = {6, 3};
			allowOwnedCargoManipulation = 1;
			openable = "false";
		};
	};
};
