// config.bin - 12:10:39 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Ind_Coltan_Mine {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Ind_Coltan_Main_EP1 : HouseNoDestruct {
		armor = 600;
		model = "DZ\structures\Ind_Coltan_Mine\Ind_Coltan_Main_EP1.p3d";
		ladders[] = {{"start1", "end1"}, {"start2", "end2"}};
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
			
			class Doors2 {
				displayName = "door 2";
				component = "Doors2";
				soundPos = "doors2_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.6;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_ind_coltan_hopper_ep1 : HouseNoDestruct {
		model = "dz\structures\ind_coltan_mine\ind_coltan_hopper_ep1.p3d";
	};
	
	class Land_Ind_Coltan_Conv1_Main_EP1 : HouseNoDestruct {
		model = "dz\structures\ind_coltan_mine\ind_coltan_conv1_main_ep1.p3d";
	};
	
	class Land_Ind_Coltan_Conv1_End_EP1 : HouseNoDestruct {
		model = "dz\structures\ind_coltan_mine\ind_coltan_conv1_end_ep1.p3d";
	};
	
	class Land_Ind_Coltan_Conv1_10_EP1 : HouseNoDestruct {
		model = "dz\structures\ind_coltan_mine\ind_coltan_conv1_10_ep1.p3d";
	};
	
	class Land_Ind_Coltan_Conv2_EP1 : HouseNoDestruct {
		model = "dz\structures\ind_coltan_mine\ind_coltan_conv2_ep1.p3d";
	};
	
	class Land_Misc_Coltan_Heap_EP1 : HouseNoDestruct {
		model = "dz\structures\ind_coltan_mine\misc_coltan_heap_ep1.p3d";
	};
};
