// config.bin - 12:13:14 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Ruins {
		units[] = {"Land_ruin_corner_1", "Land_ruin_corner_2", "Land_ruin_chimney", "Land_ruin_wall", "Land_ruin_walldoor", "Land_ruin_rubble", "Land_ruin_01"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_ruin_corner_1 : HouseNoDestruct {
		armor = 800;
		model = "\dz\structures\Ruins\ruin_corner_1.p3d";
	};
	
	class Land_ruin_corner_2 : Land_ruin_corner_1 {
		model = "\dz\structures\Ruins\ruin_corner_2.p3d";
	};
	
	class Land_ruin_chimney : Land_ruin_corner_1 {
		model = "\dz\structures\Ruins\ruin_chimney.p3d";
	};
	
	class Land_ruin_wall : Land_ruin_corner_1 {
		model = "\dz\structures\Ruins\ruin_wall.p3d";
	};
	
	class Land_ruin_walldoor : Land_ruin_corner_1 {
		model = "\dz\structures\Ruins\ruin_walldoor.p3d";
	};
	
	class Land_ruin_rubble : Land_ruin_corner_1 {
		model = "\dz\structures\Ruins\ruin_rubble.p3d";
	};
	
	class Land_ruin_01 : Land_ruin_corner_1 {
		model = "\dz\structures\Ruins\ruin_01.p3d";
	};
};
