// config.bin - 21:38:14 06/19/17, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Mil {
		units[] = {"Land_Mil_ControlTower", "Land_Mil_House", "Land_Mil_Barracks_i", "Land_Mil_Barracks", "Land_Mil_Barracks_L", "Land_Mil_Guardhouse"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Mil_ControlTower : HouseNoDestruct {
		scope = protected;
		model = "\dz\structures\Mil\Mil_ControlTower.p3d";
		displayName = "Control Tower";
		ladders[] = {{"start1", "end1"}, {"start2", "end2"}};
		
		class AnimationSources {
			class doorstwin1 {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.4;
			};
			
			class doors3 : doorstwin1 {
				initOpened = 0.2;
			};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "twin1_action";
				radius = 3;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doorstwin1') < 0.5)";
				statement = "(this animateSource ['doorstwin1', 1])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doorstwin1') >= 0.5)";
				statement = "(this animateSource ['doorstwin1', 0])";
			};
			
			class OpenDoors_2 : OpenDoors_1 {
				position = "doors3_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors3') < 0.5)";
				statement = "(this animateSource ['doors3', 1])";
			};
			
			class CloseDoors_2 : CloseDoors_1 {
				position = "doors3_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors3') >= 0.5)";
				statement = "(this animateSource ['doors3', 0])";
			};
		};
	};
	
	class Land_Mil_House : HouseNoDestruct {
		scope = protected;
		model = "\dz\structures\Mil\Mil_House.p3d";
		displayName = "Military House";
		
		class AnimationSources {
			class doorstwin1 {
				source = "user";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.4;
			};
			
			class doors3 : doorstwin1 {
				initOpened = 0.2;
			};
			
			class doors4 : doorstwin1 {
				initOpened = 0.5;
			};
			
			class doors5 : doorstwin1 {
				initOpened = 0.7;
			};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "doorstwin1_action";
				radius = 2;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doorstwin1') >= 0.5)";
				statement = "(this animateSource ['doorstwin1', 0])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doorstwin1') < 0.5)";
				statement = "(this animateSource ['doorstwin1', 1])";
			};
			
			class OpenDoors_2 : OpenDoors_1 {
				position = "doors3_action";
				condition = "((this animationSourcePhase 'doors3') >= 0.5)";
				statement = "(this animateSource ['doors3', 0])";
			};
			
			class CloseDoors_2 : CloseDoors_1 {
				position = "doors3_action";
				condition = "((this animationSourcePhase 'doors3') < 0.5)";
				statement = "(this animateSource ['doors3', 1])";
			};
			
			class OpenDoors_3 : OpenDoors_1 {
				position = "doors4_action";
				condition = "((this animationSourcePhase 'doors4') >= 0.5)";
				statement = "(this animateSource ['doors4', 0])";
			};
			
			class CloseDoors_3 : CloseDoors_1 {
				position = "doors4_action";
				condition = "((this animationSourcePhase 'doors4') < 0.5)";
				statement = "(this animateSource ['doors4', 1])";
			};
			
			class OpenDoors_4 : OpenDoors_1 {
				position = "doors5_action";
				condition = "((this animationSourcePhase 'doors5') >= 0.5)";
				statement = "(this animateSource ['doors5', 0])";
			};
			
			class CloseDoors_4 : CloseDoors_1 {
				position = "doors5_action";
				condition = "((this animationSourcePhase 'doors5') < 0.5)";
				statement = "(this animateSource ['doors5', 1])";
			};
		};
	};
	
	class Land_Mil_Barracks_i : HouseNoDestruct {
		scope = protected;
		model = "\dz\structures\Mil\Mil_Barracks_i.p3d";
		displayName = "Military Barracks";
		
		class AnimationSources {
			class doors1 {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.3;
			};
			
			class doors2 : doors1 {
				initOpened = 0.4;
			};
			
			class doors3 : doors1 {
				initOpened = 0.2;
			};
			
			class doors4 : doors1 {
				initOpened = 0.5;
			};
			
			class doors5 : doors1 {
				initOpened = 0.7;
			};
			
			class doors6 : doors1 {
				initOpened = 0.6;
			};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "doors1_action";
				radius = 1.5;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doors1') < 0.5)";
				statement = "(this animateSource ['doors1', 1])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doors1') >= 0.5)";
				statement = "(this animateSource ['doors1', 0])";
			};
			
			class OpenDoors_2 : OpenDoors_1 {
				position = "doors2_action";
				condition = "((this animationSourcePhase 'doors2') < 0.5)";
				statement = "(this animateSource ['doors2', 1])";
			};
			
			class CloseDoors_2 : CloseDoors_1 {
				position = "doors2_action";
				condition = "((this animationSourcePhase 'doors2') >= 0.5)";
				statement = "(this animateSource ['doors2', 0])";
			};
			
			class OpenDoors_3 : OpenDoors_1 {
				position = "doors3_action";
				condition = "((this animationSourcePhase 'doors3') < 0.5)";
				statement = "(this animateSource ['doors3', 1])";
			};
			
			class CloseDoors_3 : CloseDoors_1 {
				position = "doors3_action";
				condition = "((this animationSourcePhase 'doors3') >= 0.5)";
				statement = "(this animateSource ['doors3', 0])";
			};
			
			class OpenDoors_4 : OpenDoors_1 {
				position = "doors4_action";
				condition = "((this animationSourcePhase 'doors4') < 0.5)";
				statement = "(this animateSource ['doors4', 1])";
			};
			
			class CloseDoors_4 : CloseDoors_1 {
				position = "doors4_action";
				condition = "((this animationSourcePhase 'doors4') >= 0.5)";
				statement = "(this animateSource ['doors4', 0])";
			};
			
			class OpenDoors_5 : OpenDoors_1 {
				position = "doors5_action";
				condition = "((this animationSourcePhase 'doors5') < 0.5)";
				statement = "(this animateSource ['doors5', 1])";
			};
			
			class CloseDoors_5 : CloseDoors_1 {
				position = "doors5_action";
				condition = "((this animationSourcePhase 'doors5') >= 0.5)";
				statement = "(this animateSource ['doors5', 0])";
			};
			
			class OpenDoors_6 : OpenDoors_1 {
				position = "doors6_action";
				condition = "((this animationSourcePhase 'doors6') < 0.5)";
				statement = "(this animateSource ['doors6', 1])";
			};
			
			class CloseDoors_6 : CloseDoors_1 {
				position = "doors6_action";
				condition = "((this animationSourcePhase 'doors6') >= 0.5)";
				statement = "(this animateSource ['doors6', 0])";
			};
			
			class OpenDoors_7 : OpenDoors_1 {
				position = "doors7_action";
				condition = "((this animationSourcePhase 'doors7') < 0.5)";
				statement = "(this animateSource ['doors7', 1])";
			};
			
			class CloseDoors_7 : CloseDoors_1 {
				position = "doors7_action";
				condition = "((this animationSourcePhase 'doors7') >= 0.5)";
				statement = "(this animateSource ['doors7', 0])";
			};
		};
	};
	
	class Land_Mil_Barracks : HouseNoDestruct {
		scope = protected;
		model = "\dz\structures\Mil\Mil_Barracks.p3d";
		displayName = "Military Barracks";
		
		class AnimationSources {
			class doorstwin1 {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.6;
			};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "doorstwin1_action";
				radius = 3;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doorstwin1') < 0.5)";
				statement = "(this animateSource ['doorstwin1', 1])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doorstwin1') >= 0.5)";
				statement = "(this animateSource ['doorstwin1', 0])";
			};
		};
	};
	
	class Land_Mil_Barracks_L : HouseNoDestruct {
		scope = protected;
		model = "\dz\structures\Mil\Mil_Barracks_L.p3d";
		displayName = "Military Barracks L";
		
		class AnimationSources {
			class doorstwin1 {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.1;
			};
			
			class doors3 : doorstwin1 {};
			
			class doors4 : doorstwin1 {};
			
			class doors5 : doorstwin1 {};
			
			class doors6 : doorstwin1 {};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "doorstwin1_action";
				radius = 3;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doorstwin1') < 0.5)";
				statement = "(this animateSource ['doorstwin1', 1])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doorstwin1') >= 0.5)";
				statement = "(this animateSource ['doorstwin1', 0])";
			};
			
			class OpenDoors_2 : OpenDoors_1 {
				position = "doors3_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors3') < 0.5)";
				statement = "(this animateSource ['doors3', 1])";
			};
			
			class CloseDoors_2 : CloseDoors_1 {
				position = "doors3_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors3') >= 0.5)";
				statement = "(this animateSource ['doors3', 0])";
			};
			
			class OpenDoors_3 : OpenDoors_1 {
				position = "doors4_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors4') < 0.5)";
				statement = "(this animateSource ['doors4', 1])";
			};
			
			class CloseDoors_3 : CloseDoors_1 {
				position = "doors4_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors4') >= 0.5)";
				statement = "(this animateSource ['doors4', 0])";
			};
			
			class OpenDoors_4 : OpenDoors_1 {
				position = "doors5_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors5') < 0.5)";
				statement = "(this animateSource ['doors5', 1])";
			};
			
			class CloseDoors_4 : CloseDoors_1 {
				position = "doors5_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors5') >= 0.5)";
				statement = "(this animateSource ['doors5', 0])";
			};
			
			class OpenDoors_5 : OpenDoors_1 {
				position = "doors6_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors6') < 0.5)";
				statement = "(this animateSource ['doors6', 1])";
			};
			
			class CloseDoors_5 : CloseDoors_1 {
				position = "doors6_action";
				radius = 2;
				condition = "((this animationSourcePhase 'doors6') >= 0.5)";
				statement = "(this animateSource ['doors6', 0])";
			};
		};
	};
	
	class Land_Mil_Guardhouse : HouseNoDestruct {
		scope = protected;
		model = "\dz\structures\Mil\Mil_Guardhouse.p3d";
		
		class AnimationSources {
			class doors1 {
				source = "user";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.4;
			};
			
			class doors2 : doors1 {
				initOpened = 0.4;
			};
			
			class doors3 : doors1 {
				initOpened = 0.2;
			};
			
			class doors4 : doors1 {
				initOpened = 0.5;
			};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "doors1_action";
				radius = 2;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doors1') >= 0.5)";
				statement = "(this animateSource ['doors1', 0])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doors1') < 0.5)";
				statement = "(this animateSource ['doors1', 1])";
			};
			
			class OpenDoors_2 : OpenDoors_1 {
				position = "doors2_action";
				condition = "((this animationSourcePhase 'doors2') >= 0.5)";
				statement = "(this animateSource ['doors2', 0])";
			};
			
			class CloseDoors_2 : CloseDoors_1 {
				position = "doors2_action";
				condition = "((this animationSourcePhase 'doors2') < 0.5)";
				statement = "(this animateSource ['doors2', 1])";
			};
			
			class OpenDoors_3 : OpenDoors_1 {
				position = "doors3_action";
				condition = "((this animationSourcePhase 'doors3') >= 0.5)";
				statement = "(this animateSource ['doors3', 0])";
			};
			
			class CloseDoors_3 : CloseDoors_1 {
				position = "doors3_action";
				condition = "((this animationSourcePhase 'doors3') < 0.5)";
				statement = "(this animateSource ['doors3', 1])";
			};
		};
	};
	
	class Land_Mil_GuardTower : HouseNoDestruct {
		scope = protected;
		model = "\dz\structures\Mil\Mil_GuardTower.p3d";
	};
};
