// config.bin - 11:59:56 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class DZ_Buildings2_BuildingParts_Signs_TEC {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Buildings2_BuildingParts_Signs"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class Land_Tec : House {
		armor = 5;
		model = "dz\buildings2\BuildingParts\Signs\TEC\tec.p3d";
		
		class DestructionEffects {
			class DestroyPhase1 {
				simulation = "destroy";
				type = "DelayedDestruction";
				lifeTime = 2.5;
				position = "";
				intensity = 1;
				interval = 1;
			};
		};
	};
};
