// config.bin - 12:07:55 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Nav_Boathouse {
		units[] = {"Land_Nav_Boathouse"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Nav_Boathouse : HouseNoDestruct {
		model = "\dz\structures\Nav_Boathouse\Nav_Boathouse.p3d";
		ladders[] = {{"start1", "end1"}};
		
		class Damage {
			tex[] = {};
			mat[] = {};
		};
	};
	
	class Land_Nav_Boathouse_PierL : HouseNoDestruct {
		model = "\dz\structures\Nav_Boathouse\Nav_Boathouse_PierL.p3d";
		
		class Damage {
			tex[] = {};
			mat[] = {};
		};
	};
	
	class Land_Nav_Boathouse_PierR : Land_Nav_Boathouse_PierL {
		model = "\dz\structures\Nav_Boathouse\Nav_Boathouse_PierR.p3d";
	};
	
	class Land_Nav_Boathouse_PierT : Land_Nav_Boathouse_PierL {
		model = "\dz\structures\Nav_Boathouse\Nav_Boathouse_PierT.p3d";
	};
};
