// config.bin - 11:18:58 05/22/17, generated in 0.05 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Worlds_Chernarusplus_World {
		units[] = {"FXCrWindLeaf1", "FXCrWindLeaf2", "FXCrWindLeaf3"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2", "DZ_Structures", "DZ_Roads2", "DZ_Rocks2", "DZ_Signs2", "DZ_Misc", "DZ_Misc2", "DZ_Misc3"};
	};
};

class CfgVehicles {
	class ThingEffect;	// External class reference
	class ThingEffectLight;	// External class reference
	class ThingEffectFeather;	// External class reference
	
	class FXCrWindLeaf1 : ThingEffectLight {
		scope = protected;
		model = "\dz\plants2\clutter\cr_leaf.p3d";
		displayName = "Internal: FxCrWindLeaf1";
		airFriction2[] = {2, 2, 8};
		airFriction1[] = {1, 1, 4};
		airFriction0[] = {0.3, 0.3, 0.1};
		airRotation = 0.35;
		minHeight = 0.3;
		avgHeight = 5.5;
		maxHeight = 10.0;
	};
	
	class FXCrWindLeaf2 : FXCrWindLeaf1 {
		model = "\dz\plants2\clutter\cr_leaf2.p3d";
		displayName = "Internal: FxCrWindLeaf2";
	};
	
	class FXCrWindLeaf3 : FXCrWindLeaf1 {
		model = "\dz\plants2\clutter\cr_leaf3.p3d";
		displayName = "Internal: FxCrWindLeaf3";
	};
};

class CfgWorlds {
	class DefaultWorld {
		class Weather;	// External class reference
		class Grid;	// External class reference
	};
	
	class CAWorld : DefaultWorld {
		class Grid : Grid {};
		class DayLightingBrightAlmost;	// External class reference
		class DayLightingRainy;	// External class reference
		class DefaultClutter;	// External class reference
		
		class Weather : Weather {
			class Lighting;	// External class reference
		};
	};
	class DefaultLighting;	// External class reference
	
	class ChernarusPlus : CAWorld {
		access = ReadOnlyVerified;
		worldId = 1;
		cutscenes[] = {"ChernarusPlusIntro1"};
		description = "Chernarus";
		icon = "";
		worldName = "\dz\Worlds\ChernarusPlus\world\ChernarusPlus.wrp";
		areaMap = "\dz\Worlds\ChernarusPlus\areamap\ChernarusPlus.map";
		proxyExportFile = "\dz\Worlds\ChernarusPlus\proxyexport\ChernarusPlus.bin";
		pictureMap = "";
		pictureShot = "\dz\Worlds\ChernarusPlus\data\ui_selectisland_ChernarusPlus_ca.paa";
		
		class Navmesh {
			navmeshName = "\dz\Worlds\chernarusplus\navmesh\navmesh.nm";
			filterIsolatedIslandsOnLoad = 1;
			
			class GenParams {
				tileWidth = 50.0;
				cellSize1 = 0.25;
				cellSize2 = 0.1;
				cellSize3 = 0.1;
				filterIsolatedIslands = 1;
				seedPosition[] = {7500, 0, 7500};
				
				class Agent {
					diameter = 0.6;
					standHeight = 1.5;
					crouchHeight = 1.0;
					proneHeight = 0.5;
					maxStepHeight = 0.4;
					maxSlope = 45.0;
				};
				
				class Links {
					class ZedJump387_050 {
						jumpLength = 1.5;
						jumpHeight = 0.5;
						minCenterHeight = 0.3;
						jumpDropdownMin = 0.5;
						jumpDropdownMax = -0.5;
						areaType = "jump0";
						flags[] = {"jumpOver"};
						color = 1727987712;
					};
					
					class ZedJump387_110 {
						jumpLength = 3.9;
						jumpHeight = 1.1;
						minCenterHeight = 0.8;
						jumpDropdownMin = 0.5;
						jumpDropdownMax = -0.5;
						areaType = "jump0";
						flags[] = {"jumpOver"};
						color = 1711308800;
					};
					
					class ZedJump420_160 {
						jumpLength = 4.25;
						jumpHeight = 1.8;
						minCenterHeight = 1.2;
						jumpDropdownMin = 0.5;
						jumpDropdownMax = -0.5;
						areaType = "jump0";
						flags[] = {"jumpOver"};
						color = 1711276287;
					};
					
					class ZedJump265_210 {
						jumpLength = 2.45;
						jumpHeight = 2.5;
						minCenterHeight = 1.8;
						jumpDropdownMin = 0.5;
						jumpDropdownMax = -0.5;
						areaType = "jump0";
						flags[] = {"climb"};
						color = 1720975571;
					};
					
					class Fence50_110deer {
						jumpLength = 8.0;
						jumpHeight = 1.1;
						minCenterHeight = 0.5;
						jumpDropdownMin = 1.0;
						jumpDropdownMax = -1.0;
						areaType = "jump2";
						flags[] = {"jumpOver"};
						color = 1722460927;
					};
					
					class Fence110_160deer {
						jumpLength = 8.0;
						jumpHeight = 1.6;
						minCenterHeight = 1.1;
						jumpDropdownMin = 1.0;
						jumpDropdownMax = -1.0;
						areaType = "jump3";
						flags[] = {"jumpOver"};
						color = 1713700856;
					};
					
					class Fence50_110hen {
						jumpLength = 4.0;
						jumpHeight = 1.1;
						minCenterHeight = 0.5;
						jumpDropdownMin = 0.5;
						jumpDropdownMax = -0.5;
						areaType = "jump4";
						flags[] = {"jumpOver"};
						color = 1728053162;
					};
					
					class Fence110_160hen {
						jumpLength = 4.0;
						jumpHeight = 1.6;
						minCenterHeight = 1.1;
						jumpDropdownMin = 0.5;
						jumpDropdownMax = -0.5;
						areaType = "jump4";
						flags[] = {"jumpOver"};
						color = 1728053162;
					};
				};
			};
		};
		plateFormat = "ML$ - #####";
		plateLetters = ABCDEGHIKLMNOPRSTVXZ;
		longitude = 30;	// positive is east
		latitude = -45;	// positive is south
		
		class OutsideTerrain {
			satellite = "dz\Worlds\ChernarusPlus\data\s_satout_co.paa";
			enableTerrainSynth = 1;
			
			class Layers {
				class Layer0 {
					nopx = "dz\Worlds\ChernarusPlus\data\cr_trava1_detail_nopx.paa";
					texture = "dz\Worlds\ChernarusPlus\data\cr_trava1_detail_co.paa";
				};
			};
		};
		
		class Grid : Grid {
			offsetX = 0;
			offsetY = 0;
			
			class Zoom1 {
				zoomMax = 0.15;
				format = "XY";
				formatX = 000;
				formatY = 000;
				stepX = 100;
				stepY = 100;
			};
			
			class Zoom2 {
				zoomMax = 0.85;
				format = "XY";
				formatX = "00";
				formatY = "00";
				stepX = 1000;
				stepY = 1000;
			};
			
			class Zoom3 {
				zoomMax = 1e+030;
				format = "XY";
				formatX = "0";
				formatY = "0";
				stepX = 10000;
				stepY = 10000;
			};
		};
		startTime = 9:20;
		startDate = 11/10/2008;
		startWeather = 0.25;
		startFog = 0.0;
		forecastWeather = 0.25;
		forecastFog = 0.0;
		centerPosition[] = {7100, 7750, 300};
		seagullPos[] = {1272.84, 150.0, 14035};
		ilsPosition[] = {4887.5, 9660};
		ilsDirection[] = {0.5075, 0.08, -0.8616};
		ilsTaxiIn[] = {4785.21, 10174.3, 5024.9, 9759.07, 5027.38, 9737.02, 5015.33, 9721.14, 4928.96, 9670.51, 4906.1, 9664.37, 4880.94, 9673.65};
		ilsTaxiOff[] = {4671, 10038, 4195.5, 10862, 4201.01, 10885.8, 4218.54, 10899.8, 4304.68, 10950.2, 4324.96, 10953.7, 4345.75, 10938.9, 4785.21, 10174.3};
		drawTaxiway = 1;
		
		class SecondaryAirports {
			class ChernarusPlusAirstrip1 {
				ilsPosition[] = {12461, 12585};
				ilsDirection[] = {0.9396, 0.08, -0.342};
				ilsTaxiIn[] = {12125.9, 12669.3, 12435.5, 12562.1, 12442, 12561, 12447, 12564, 12453.3, 12575.2, 12454.3, 12581, 12451.4, 12586};
				ilsTaxiOff[] = {12204.4, 12681.9, 11812.1, 12824.1, 11804.1, 12824.4, 11797.8, 12818.8, 11790.9, 12801.5, 11790.6, 12793.6, 11796.6, 12788.6, 12125.9, 12669.3};
				drawTaxiway = 0;
			};
			
			class ChernarusPlusAirstrip2 {
				ilsPosition[] = {5223, 2220.5};
				ilsDirection[] = {0.866, 0.08, -0.5};
				ilsTaxiIn[] = {5009.9, 2374.2, 5240.3, 2243.2, 5243.3, 2238.4, 5242.7, 2232.1, 5235.9, 2221.1, 5229.7, 2216.6, 5221.5, 2217.3};
				ilsTaxiOff[] = {5070, 2308, 4640.8, 2551.9, 4638.3, 2557, 4639.3, 2563.3, 4646.5, 2573.9, 4651.3, 2578.5, 4658.5, 2577.9, 5009.9, 2374.2};
				drawTaxiway = 0;
			};
		};
		
		class ReplaceObjects {};
		
		class Sounds {
			sounds[] = {};
		};
		
		class Animation {
			vehicles[] = {};
		};
		
		class Lighting : DefaultLighting {
			groundReflection[] = {0.06, 0.06, 0.03};
		};
		
		class DayLightingBrightAlmost : DayLightingBrightAlmost {
			deepNight[] = {-15, {0.05, 0.05, 0.06}, {0.001, 0.001, 0.002}, {0.02, 0.02, 0.05}, {0.003, 0.003, 0.003}, {0.0001, 0.0001, 0.0002}, {0.0001, 0.0001, 0.0002}, 0};
			fullNight[] = {-5, {0.05, 0.05, 0.05}, {0.02, 0.02, 0.02}, {0.04, 0.04, 0.04}, {0.04, 0.04, 0.04}, {0.01, 0.01, 0.02}, {0.08, 0.06, 0.06}, 0};
			sunMoon[] = {-3.75, {0.045, 0.04, 0.04}, {0.04, 0.04, 0.04}, {0.045, 0.04, 0.04}, {0.04, 0.04, 0.04}, {0.04, 0.035, 0.04}, {0.1, 0.08, 0.09}, 0.5};
			earlySun[] = {-2.5, {0.12, 0.1, 0.1}, {0.08, 0.06, 0.07}, {0.12, 0.1, 0.1}, {0.08, 0.06, 0.07}, {0.08, 0.07, 0.08}, {0.1, 0.1, 0.12}, 1};
			sunrise[] = {0, {{0.7, 0.45, 0.45}, 5.16+(-4)}, {{0.07, 0.09, 0.12}, 4.0+(-4)}, {{0.6, 0.47, 0.25}, 4.66+(-4)}, {{0.1, 0.09, 0.1}, 4.3+(-4)}, {{0.5, 0.4, 0.4}, 6.49+(-4)}, {{0.88, 0.51, 0.24}, 8.39+(-4)}, 1};
			earlyMorning[] = {3, {{0.65, 0.55, 0.55}, 6.04+(-4)}, {{0.08, 0.09, 0.11}, 4.5+(-4)}, {{0.55, 0.47, 0.25}, 5.54+(-4)}, {{0.1, 0.09, 0.1}, 5.02+(-4)}, {{0.5, 0.4, 0.4}, 7.05+(-4)}, {{0.88, 0.51, 0.24}, 8.88+(-4)}, 1};
			midMorning[] = {8, {{0.98, 0.85, 0.8}, 8.37+(-4)}, {{0.08, 0.09, 0.11}, 6.42+(-4)}, {{0.87, 0.47, 0.25}, 7.87+(-4)}, {{0.09, 0.09, 0.1}, 6.89+(-4)}, {{0.5, 0.4, 0.4}, 8.9+(-4)}, {{0.88, 0.51, 0.24}, 10.88+(-4)}, 1};
			morning[] = {16, {{1, 1, 0.9}, 13.17+(-4)}, {{0.17, 0.18, 0.19}, 10.26+(-4)}, {{1, 1, 0.9}, 12.67+(-4)}, {{0.17, 0.18, 0.19}, 11.71+(-4)}, {{0.15, 0.15, 0.15}, 12.42+(-4)}, {{0.17, 0.17, 0.15}, 14.42+(-4)}, 1};
			noon[] = {45, {{1, 1, 1}, 17+(-4)}, {{1, 1.3, 1.55}, 13.5+(-4)}, {{1, 1, 1}, 15+(-4)}, {{0.36, 0.37, 0.38}, 13.5+(-4)}, {{1, 1, 1}, 16+(-4)}, {{1.0, 1.0, 1}, 17+(-4)}, 1};
		};
		
		class DayLightingRainy : DayLightingRainy {
			deepNight[] = {-15, {0.0034, 0.0034, 0.004}, {0.003, 0.003, 0.003}, {0.0034, 0.0034, 0.004}, {0.003, 0.003, 0.003}, {0.001, 0.001, 0.002}, {0.001, 0.001, 0.002}, 0};
			fullNight[] = {-5, {0.023, 0.023, 0.023}, {0.02, 0.02, 0.02}, {0.023, 0.023, 0.023}, {0.02, 0.02, 0.02}, {0.01, 0.01, 0.02}, {0.08, 0.06, 0.06}, 0};
			sunMoon[] = {-3.75, {0.04, 0.04, 0.05}, {0.04, 0.04, 0.05}, {0.04, 0.04, 0.05}, {0.04, 0.04, 0.05}, {0.04, 0.035, 0.04}, {0.11, 0.08, 0.09}, 0.5};
			earlySun[] = {-2.5, {0.0689, 0.0689, 0.0804}, {0.06, 0.06, 0.07}, {0.0689, 0.0689, 0.0804}, {0.06, 0.06, 0.07}, {0.08, 0.07, 0.08}, {0.14, 0.1, 0.12}, 0.5};
			earlyMorning[] = {0, {{1, 1, 1}, (-4)+3.95}, {{1, 1, 1}, (-4)+3.0}, {{1, 1, 1}, (-4)+3.95}, {{1, 1, 1}, (-4)+3.0}, {{1, 1, 1}, (-4)+4}, {{1, 1, 1}, (-4)+5.5}, 1};
			morning[] = {5, {{1, 1, 1}, (-4)+5.7}, {{1, 1, 1}, (-4)+4.5}, {{1, 1, 1}, (-4)+5.7}, {{1, 1, 1}, (-4)+4.5}, {{1, 1, 1}, (-4)+7}, {{1, 1, 1}, (-4)+8}, 1};
			lateMorning[] = {25, {{1, 1, 1}, (-4)+10.45}, {{1, 1, 1}, (-4)+9.75}, {{1, 1, 1}, (-4)+10.45}, {{1, 1, 1}, (-4)+9.75}, {{1, 1, 1}, (-4)+12}, {{1, 1, 1}, (-4)+12.75}, 1};
			noon[] = {70, {{1, 1, 1}, (-4)+12.5}, {{1, 1, 1}, (-4)+11}, {{1, 1, 1}, (-4)+12}, {{1, 1, 1}, (-4)+11}, {{1, 1, 1}, (-4)+13.5}, {{1, 1, 1}, (-4)+14}, 1};
		};
		
		class Weather : Weather {
			class Lighting : Lighting {
				class BrightAlmost : DayLightingBrightAlmost {
					overcast = 0;
				};
				
				class Rainy : DayLightingRainy {
					overcast = 1.0;
				};
			};
		};
		clutterGrid = 1.0;
		clutterDist = 125;
		noDetailDist = 40;
		fullDetailDist = 15;
		midDetailTexture = "dz\Worlds\ChernarusPlus\data\middle_mco.paa";
		minTreesInForestSquare = 3;
		minRocksInRockSquare = 3;
		
		class clutter {
			class GrassTall : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_GrassTall.p3d";
				affectedByWind = 0.4;
				swLighting = 1;
				scaleMin = 0.7;
				scaleMax = 1.0;
			};
			
			class StubbleClutter : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_stubble.p3d";
				affectedByWind = 0.1;
				swLighting = 1;
				scaleMin = 0.9;
				scaleMax = 1.1;
			};
			
			class AutumnFlowers : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_autumn_flowers.p3d";
				affectedByWind = 0.4;
				swLighting = 1;
				scaleMin = 0.5;
				scaleMax = 0.9;
			};
			
			class GrassBunch : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_GrassBunch.p3d";
				affectedByWind = 0.35;
				swLighting = 1;
				scaleMin = 0.6;
				scaleMax = 1.0;
			};
			
			class GrassCrooked : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_GrassCrooked.p3d";
				affectedByWind = 0.3;
				swLighting = 1;
				scaleMin = 0.9;
				scaleMax = 1.15;
			};
			
			class GrassCrookedGreen : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_GrassCrookedGreen.p3d";
				affectedByWind = 0.3;
				swLighting = 1;
				scaleMin = 0.7;
				scaleMax = 1.15;
			};
			
			class GrassCrookedForest : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_GrassCrookedForest.p3d";
				affectedByWind = 0.3;
				swLighting = 1;
				scaleMin = 0.8;
				scaleMax = 1.2;
			};
			
			class WeedDead : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_WeedDead.p3d";
				affectedByWind = 0.3;
				swLighting = 1;
				scaleMin = 0.75;
				scaleMax = 1.1;
			};
			
			class WeedDeadSmall : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_WeedDead2.p3d";
				affectedByWind = 0.3;
				swLighting = 1;
				scaleMin = 0.75;
				scaleMax = 0.9;
			};
			
			class HeatherBrush : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_caluna.p3d";
				affectedByWind = 0.15;
				swLighting = 1;
				scaleMin = 0.9;
				scaleMax = 1.8;
				surfaceColor[] = {0.53, 0.5, 0.37, 1};
			};
			
			class WeedSedge : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_weed3.p3d";
				affectedByWind = 0.2;
				swLighting = 1;
				scaleMin = 0.5;
				scaleMax = 0.85;
			};
			
			class WeedTall : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_weed2.p3d";
				affectedByWind = 0.3;
				swLighting = 1;
				scaleMin = 0.8;
				scaleMax = 1.1;
			};
			
			class BlueBerry : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_BlueBerry.p3d";
				affectedByWind = 0.05;
				swLighting = 1;
				scaleMin = 0.85;
				scaleMax = 1.3;
			};
			
			class RaspBerry : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_raspBerry.p3d";
				affectedByWind = 0;
				swLighting = 1;
				scaleMin = 0.8;
				scaleMax = 1.2;
			};
			
			class FernAutumn : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_fern.p3d";
				affectedByWind = 0.1;
				scaleMin = 0.6;
				scaleMax = 1.3;
			};
			
			class FernAutumnTall : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_fernTall.p3d";
				affectedByWind = 0.15;
				scaleMin = 0.7;
				scaleMax = 1.2;
			};
			
			class SmallPicea : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_picea.p3d";
				affectedByWind = 0.05;
				scaleMin = 0.75;
				scaleMax = 1.25;
			};
			
			class PlantWideLeaf : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_WideLeafPlant.p3d";
				affectedByWind = 0.1;
				scaleMin = 1.0;
				scaleMax = 1.0;
			};
			
			class CRGrassDryBunch : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_deadGrassBunch.p3d";
				affectedByWind = 0.35;
				swLighting = 1;
				scaleMin = 0.5;
				scaleMax = 1.0;
			};
			
			class CRGrassDryLongBunch : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_grassDryLongBunch.p3d";
				affectedByWind = 0.35;
				swLighting = 1;
				scaleMin = 0.6;
				scaleMax = 1.1;
			};
			
			class CRAutumnFlowers : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_autumn_flowers.p3d";
				affectedByWind = 0.4;
				swLighting = 1;
				scaleMin = 0.7;
				scaleMax = 1.0;
			};
			
			class MushroomsHorcak : DefaultClutter {
				model = "dz\plants2\plant\clutter\c_MushroomHorcak.p3d";
				affectedByWind = 0;
				scaleMin = 0.85;
				scaleMax = 1.25;
			};
			
			class MushroomsPrasivka : MushroomsHorcak {
				model = "dz\plants2\plant\clutter\c_MushroomPrasivky.p3d";
			};
			
			class MushroomsBabka : MushroomsHorcak {
				model = "dz\plants2\plant\clutter\c_MushroomBabka.p3d";
			};
			
			class MushroomsMuchomurka : MushroomsHorcak {
				model = "dz\plants2\plant\clutter\c_MushroomMuchomurka.p3d";
			};
		};
		
		class Subdivision {
			class Fractal {
				rougness = 5;
				maxRoad = 0.02;
				maxTrack = 0.5;
				maxSlopeFactor = 0.05;
			};
			
			class WhiteNoise {
				rougness = 2;
				maxRoad = 0.01;
				maxTrack = 0.05;
				maxSlopeFactor = 0.0025;
			};
			minY = 0.0;
			minSlope = 0.02;
		};
		
		class Ambient {
			class BigInsects {
				radius = 20;
				cost = "(5 - (2 * houses)) * (1 - night) * (1 - rain) * (1 - sea) * (1 - windy)";
				
				class Species {
					class DragonFly {
						probability = "0.6 - (meadow * 0.5) + (forest * 0.4)";
						cost = 1;
					};
					
					class ButterFly {
						probability = "0.4 + (meadow * 0.5) - (forest * 0.4)";
						cost = 1;
					};
				};
			};
			
			class BigInsectsAquatic {
				radius = 20;
				cost = "(3 * sea) * (1 - night) * (1 - rain) * (1 - windy)";
				
				class Species {
					class DragonFly {
						probability = 1;
						cost = 1;
					};
				};
			};
			
			class SmallInsects {
				radius = 3;
				cost = "(12 - 8 * hills) * (1 - night) * (1 - rain) * (1 - sea) * (1 - windy)";
				
				class Species {
					class HouseFly {
						probability = "10 * deadBody";
						cost = 1;
					};
					
					class HoneyBee {
						probability = "(1 - deadBody) * (0.5 - forest * 0.1 + meadow * 0.2)";
						cost = 1;
					};
					
					class Mosquito {
						probability = "(1 - deadBody) * (0.2 * forest)";
						cost = 1;
					};
				};
			};
			
			class NightInsects {
				radius = 3;
				cost = "(9 - 8 * hills) * night * (1 - rain) * (1 - sea) * (1 - windy)";
				
				class Species {
					class Mosquito {
						probability = 1;
						cost = 1;
					};
				};
			};
			
			class WindClutter {
				radius = 10;
				cost = "((20 - 5 * rain) * (3 * (windy factor [0.2, 0.5]))) * (1 - sea)";
				
				class Species {
					class FxWindGrass1 {
						probability = "0.4 - 0.2 * hills - 0.2 * trees";
						cost = 1;
					};
					
					class FxWindGrass2 {
						probability = "0.4 - 0.2 * hills - 0.2 * trees";
						cost = 1;
					};
					
					class FxWindRock1 {
						probability = "0.4 * hills";
						cost = 1;
					};
					
					class FxCrWindLeaf1 {
						probability = "0.2 * trees";
						cost = 1;
					};
					
					class FxCrWindLeaf2 {
						probability = "0.1 * trees + 0.2";
						cost = 1;
					};
					
					class FxCrWindLeaf3 {
						probability = "0.1 * trees";
						cost = 1;
					};
				};
			};
			
			class NoWindClutter {
				radius = 15;
				cost = 8;
				
				class Species {
					class FxWindPollen1 {
						probability = 1;
						cost = 1;
					};
					
					class FxCrWindLeaf1 {
						probability = "0.2 * trees";
						cost = 1;
					};
					
					class FxCrWindLeaf2 {
						probability = "0.1 * trees + 0.2";
						cost = 1;
					};
					
					class FxCrWindLeaf3 {
						probability = "0.1 * trees";
						cost = 1;
					};
				};
			};
		};
		
		class Names {};
		safePositionAnchor[] = {9122.17, 5178.92};
		safePositionRadius = 8500;
	};
	initWorld = "ChernarusPlus";
};

class CfgWorldList {
	class ChernarusPlus {};
};

class CfgMissions {
	class Cutscenes {
		class ChernarusPlusIntro1 {
			directory = "dz\Worlds\ChernarusPlus\data\scenes\intro.ChernarusPlus";
		};
	};
};

class CfgSurfaces {
	class Default;	// External class reference
	
	class DZ_Default : Default {};
	
	class CRGrass1 : DZ_Default {
		files = "cr_trava1_*";
		rough = 0.11;
		dust = 0.1;
		soundEnviron = "grass";
		soundHit = "soft_ground";
		character = "CRGrassClutter";
		friction = 0.91;
		restitution = 0.2;
		audibility = 0.8;
		footDamage = 0.01;
		
		class Visible {
			prone = 0.2;
			kneel = 0.6;
			stand = 0.8;
		};
	};
	
	class CRGrass2 : CRGrass1 {
		files = "cr_trava2_*";
		character = "CRTallGrassClutter";
		friction = 0.905;
		restitution = 0.18;
		
		class Visible {
			prone = 0.1;
			kneel = 0.4;
			stand = 0.75;
		};
	};
	
	class CRGrassW1 : CRGrass2 {
		files = "cr_travad1_*";
		character = "CRGrassWClutter";
		friction = 0.905;
		restitution = 0.29;
	};
	
	class CRHlina : DZ_Default {
		files = "cr_hlina_*";
		rough = 0.09;
		dust = 0.1;
		soundEnviron = "dirt";
		soundHit = "soft_ground";
		audibility = 0.8;
		friction = 0.94;
		restitution = 0.34;
	};
	
	class CRForest1 : DZ_Default {
		files = "cr_les1_*";
		rough = 0.2;
		dust = 0.2;
		soundEnviron = "forest";
		soundHit = "soft_ground";
		character = "CRForestMixedClutter";
		friction = 0.93;
		restitution = 0.34;
		
		class Visible {
			prone = 0.3;
			kneel = 0.5;
			stand = 0.6;
		};
	};
	
	class CRForest2 : DZ_Default {
		files = "cr_les2_*";
		rough = 0.2;
		dust = 0.15;
		soundEnviron = "forest";
		soundHit = "soft_ground";
		character = "CRForestFirClutter";
		friction = 0.95;
		restitution = 0.16;
		
		class Visible {
			prone = 0.1;
			kneel = 0.3;
			stand = 0.5;
		};
	};
	
	class CRGrit1 : DZ_Default {
		files = "cr_sterk_*";
		rough = 0.1;
		dust = 0.25;
		soundEnviron = "gravel";
		soundHit = "hard_ground";
		friction = 0.96;
		restitution = 0.36;
		audibility = 1.2;
		footDamage = 0.5;
		
		class Visible {
			prone = 1;
			kneel = 1;
			stand = 1;
		};
	};
	
	class CRBoulders : DZ_Default {
		files = "cr_valouny_*";
		rough = 0.1;
		dust = 0.07;
		soundEnviron = "rock";
		soundHit = "hard_ground";
		character = "CRSparseGrassClutter";
		friction = 0.95;
		restitution = 0.46;
		footDamage = 1;
		
		class Visible {
			prone = 0.9;
			kneel = 0.95;
			stand = 1;
		};
	};
	
	class CRRock : DZ_Default {
		files = "cr_skala_*";
		rough = 0.2;
		dust = 0.07;
		soundEnviron = "rock";
		soundHit = "hard_ground";
		friction = 0.95;
		restitution = 0.48;
		footDamage = 1;
		
		class Visible {
			prone = 0.6;
			kneel = 0.95;
			stand = 1;
		};
	};
	
	class CRTarmac : DZ_Default {
		files = "cr_asfalt_*";
		rough = 0.08;
		dust = 0.05;
		soundEnviron = "road";
		soundHit = "hard_ground";
		friction = 0.97;
		restitution = 0.48;
		footDamage = 0.3;
	};
	
	class CRConcrete : DZ_Default {
		files = "cr_beton_*";
		rough = 0.08;
		dust = 0.05;
		soundEnviron = "concrete_ext";
		soundHit = "concrete";
		friction = 0.97;
		restitution = 0.49;
	};
	
	class Runway : DZ_Default {
		files = "runway*";
		rough = 0.11;
		dust = 0.1;
		soundEnviron = "road";
		soundHit = "soft_ground";
		character = "CRGrassClutter";
		friction = 0.99;
		restitution = 0.5;
		footDamage = 0.01;
		
		class Visible {
			prone = 0.2;
			kneel = 0.6;
			stand = 0.8;
		};
	};
};

class CfgSurfaceCharacters {
	class CRSparseGrassClutter {
		names[] = {"CRGrassDryBunch"};
		probability[] = {0.07};
	};
	
	class CRGrassClutter {
		probability[] = {0.5, 0.1, 0.07, 0.01};
		names[] = {"GrassCrookedGreen", "GrassCrooked", "AutumnFlowers", "WeedDead"};
	};
	
	class CRTallGrassClutter {
		probability[] = {0.4, 0.2, 0.3, 0.07, 0.02, 0.01};
		names[] = {"GrassTall", "AutumnFlowers", "GrassBunch", "GrassCrooked", "WeedDead", "WeedDeadSmall"};
	};
	
	class CRGrassWClutter {
		probability[] = {0.95, 0.02, 0.03, 0.02};
		names[] = {"CRGrassDryBunch", "CRGrassDryLongBunch", "CRAutumnFlowers", "WeedDeadSmall"};
	};
	
	class CRForestMixedClutter {
		probability[] = {0.1, 0.1, 0.2};
		names[] = {"GrassCrookedForest", "FernAutumn", "FernAutumnTall"};
	};
	
	class CRForestFirClutter {
		probability[] = {0.35, 0.15, 0.12, 0.03, 0.05};
		names[] = {"BlueBerry", "FernAutumn", "FernAutumnTall", "SmallPicea", "RaspBerry"};
	};
};
