// config.bin - 12:11:48 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Misc_Misc_Caravan {
		units[] = {"Land_caravan_metal_green", "Land_caravan_metal_rust", "Land_caravan_wood_brown", "Land_caravan_wood_green"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures_Misc"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_misc_caravan_metal_green : HouseNoDestruct {
		armor = 100;
		model = "\DZ\structures\Misc\Misc_Caravan\misc_caravan_metal_green.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_misc_caravan_metal_rust : Land_misc_caravan_metal_green {
		model = "\DZ\structures\Misc\Misc_Caravan\misc_caravan_metal_rust.p3d";
	};
	
	class Land_misc_caravan_wood_brown : Land_misc_caravan_metal_green {
		model = "\DZ\structures\Misc\Misc_Caravan\misc_caravan_wood_brown.p3d";
	};
	
	class Land_misc_caravan_wood_green : Land_misc_caravan_metal_green {
		model = "\DZ\structures\Misc\Misc_Caravan\misc_caravan_wood_green.p3d";
	};
};
