// config.bin - 11:35:02 05/22/17, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_ModuleZ {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class cfgBody {
	class Head {
		hitPoint = "HitHead";
		inventorySlots[] = {"headgear", "eyewear", "mask"};
	};
	
	class Neck : Head {};
	
	class Neck1 : Head {};
	
	class Chest {
		hitPoint = "HitBody";
		inventorySlots[] = {"vest", "body", "back", "underwear", "gloves"};
	};
	
	class Spine : Chest {};
	
	class Spine1 : Chest {};
	
	class Spine2 : Chest {};
	
	class Spine3 : Chest {};
	
	class LeftArm {
		hitPoint = "HitHands";
		inventorySlots[] = {"body"};
	};
	
	class LeftShoulder : LeftArm {};
	
	class LeftArmRoll : LeftArm {};
	
	class LeftForeArm : LeftArm {};
	
	class LeftForeArmRoll : LeftArm {};
	
	class LeftHand : LeftArm {};
	
	class RightArm {
		hitPoint = "HitHands";
		inventorySlots[] = {"body"};
	};
	
	class RightShoulder : RightArm {};
	
	class RightArmRoll : RightArm {};
	
	class RightForeArm : RightArm {};
	
	class RightForeArmRoll : RightArm {};
	
	class RightHand : RightArm {};
	
	class Pelvis {
		hitPoint = "HitLegs";
		inventorySlots[] = {"legs"};
	};
	
	class LeftLeg {
		hitPoint = "HitLegs";
		inventorySlots[] = {"legs"};
	};
	
	class LeftUpLeg : LeftLeg {};
	
	class LeftUpLegRoll : LeftLeg {};
	
	class LeftLegRoll : LeftLeg {};
	
	class RightLeg {
		hitPoint = "HitLegs";
		inventorySlots[] = {"legs"};
	};
	
	class RightUpLeg : RightLeg {};
	
	class RightUpLegRoll : RightLeg {};
	
	class RightLegRoll : RightLeg {};
	
	class LeftFoot {
		hitPoint = "HitFeet";
		inventorySlots[] = {"feet"};
	};
	
	class LeftToeBase : LeftFoot {};
	
	class RightFoot {
		hitPoint = "HitFeet";
		inventorySlots[] = {"feet"};
	};
	
	class RightToeBase : RightFoot {};
};

class cfgNotifications {
	class Sickness {};
	
	class Bleeding {};
	
	class Hunger {};
	
	class Thirst {};
};

class CfgExperiences {
	class Hunter {
		class Skinning {
			class level0 {
				requiredExp = 0;
				efficiency = 0.5;
				someString = "STRING LEVEL 0";
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 0.75;
				someString = "STRING LEVEL 1";
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.0;
				someString = "STRING LEVEL 2";
			};
		};
	};
	
	class Tailor {
		class Repairing {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
				toolDamage = 0.1;
				canRepairToPristine = 0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.0;
				toolDamage = 0.075;
				canRepairToPristine = 0;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 2.0;
				toolDamage = 0.05;
				canRepairToPristine = 0;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 2.0;
				toolDamage = 0.025;
				canRepairToPristine = 1;
			};
		};
	};
	
	class Medic {
		class Bandaging {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.3;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.7;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 2.0;
			};
		};
		
		class Fixating {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.3;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.7;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 2.0;
			};
		};
		
		class TransfusionTest {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.3;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.7;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 2.0;
			};
		};
		
		class TransfusionCollect {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.3;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.7;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 2.0;
			};
		};
		
		class TransfusionGive {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.1;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.2;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 1.3;
			};
		};
		
		class SalineGive {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.1;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.2;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 1.3;
			};
		};
	};
	
	class Farmer {
		class SoilPreparation {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.1;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.2;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 1.3;
			};
		};
		
		class Fertilization {
			class level0 {
				requiredExp = 0;
				efficiency = 1.0;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.1;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.2;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 1.3;
			};
		};
		
		class Harvesting {
			class level0 {
				requiredExp = 0;
				efficiency = 1.1;
			};
			
			class level1 {
				requiredExp = 2;
				efficiency = 1.2;
			};
			
			class level2 {
				requiredExp = 4;
				efficiency = 1.3;
			};
			
			class level3 {
				requiredExp = 6;
				efficiency = 1.4;
			};
		};
	};
};

class CfgHorticulture {
	class Plants {
		class EN5C_Plant_Pepper {
			infestedTex = "dz\plants2\farming\data\pepper_plant_insect_co.paa";
			infestedMat = "";
			healthyTex = "dz\plants2\farming\data\pepper_plant_co.paa";
			healthyMat = "dz\plants2\farming\data\pepper_plant.rvmat";
		};
		
		class EN5C_Plant_Tomato {
			infestedTex = "dz\plants2\farming\data\tomato_plant_insect_co.paa";
			infestedMat = "";
			healthyTex = "dz\plants2\farming\data\tomato_plant_co.paa";
			healthyMat = "dz\plants2\farming\data\tomato_plant.rvmat";
		};
		
		class EN5C_Plant_Zucchini {
			infestedTex = "dz\plants2\farming\data\zucchini_plant_insect_co.paa";
			infestedMat = "";
			healthyTex = "dz\plants2\farming\data\zucchini_plant_co.paa";
			healthyMat = "dz\plants2\farming\data\zucchini_plant.rvmat";
		};
		
		class EN5C_Plant_Potato {
			infestedTex = "dz\plants2\farming\data\potato_plant_insect_co.paa";
			infestedMat = "dz\plants2\farming\data\potato_plant_insect.rvmat";
			healthyTex = "dz\plants2\farming\data\potato_plant_co.paa";
			healthyMat = "dz\plants2\farming\data\potato_plant.rvmat";
		};
		
		class EN5C_Plant_Pumpkin {
			infestedTex = "dz\plants2\farming\data\pumpkin_plant_insect_co.paa";
			infestedMat = "";
			healthyTex = "dz\plants2\farming\data\pumpkin_plant_co.paa";
			healthyMat = "dz\plants2\farming\data\pumpkin_plant.rvmat";
		};
		
		class EN5C_Plant_Cannabis {
			infestedTex = "dz\plants2\farming\data\cannabis_plant_insect_co.paa";
			infestedMat = "dz\plants2\farming\data\cannabis_plant_insect.rvmat";
			healthyTex = "dz\plants2\farming\data\cannabis_plant_co.paa";
			healthyMat = "dz\plants2\farming\data\cannabis_plant.rvmat";
		};
	};
};

class cfgCharacterCreation {
	format = "SurvivorParts%1%2";
	gender[] = {"Female", "Male"};
	race[] = {"African", "Indian", "Latino", "Asian", "White"};
	skin[] = {"Very Dark", "Dark", "Medium", "Light", "Very Light"};
	top[] = {"TShirtBeige", "TShirtBlack", "TShirtBlue", "TShirtGreen", "TShirtRed", "TShirtWhite", "TShirtGrey"};
	bottom[] = {"Jeans_Black", "Jeans_BlueDark", "Jeans_Blue", "Jeans_Brown", "Jeans_Green", "Jeans_Grey", "CanvasPants_Beige", "CanvasPants_Blue", "CanvasPants_Grey"};
	shoe[] = {"AthleticShoes_Black", "AthleticShoes_Blue", "AthleticShoes_Brown", "AthleticShoes_Green", "AthleticShoes_Grey"};
	maleCustom[] = {"Dean", "Matt"};
	femaleCustom[] = {"Kamila", "Henriet", "JanaZ"};
};

class PreloadVehicles {
	class SurvivorPartsMaleWhite {
		loadStyle = 1;
	};
	
	class SurvivorPartsMaleAsian {
		loadStyle = 1;
	};
	
	class SurvivorPartsMaleLatino {
		loadStyle = 1;
	};
	
	class SurvivorPartsMaleAfrican {
		loadStyle = 1;
	};
	
	class SurvivorPartsFemaleWhite {
		loadStyle = 1;
	};
	
	class SurvivorPartsFemaleAsian {
		loadStyle = 1;
	};
	
	class SurvivorPartsFemaleLatino {
		loadStyle = 1;
	};
	
	class SurvivorPartsFemaleAfrican {
		loadStyle = 1;
	};
};

class cfgCharacterScenes {
	class ChernarusPlus {
		class duskcastle1 {
			target[] = {-55262.4, 86687.6, -11729.3};
			position[] = {10255.5, 12048.3, 0.85};
			fov = 0.511;
			date[] = {3000, 6, 1, 19, 11};
			aperture = 16;
		};
		
		class forest1 {
			target[] = {47732.8, 94293.6, 7079.57};
			position[] = {4929.41, 4186.39, 1.36};
			fov = 0.471;
			date[] = {1998, 12, 9, 9, 0};
			aperture = -1;
		};
		
		class urban1 {
			target[] = {-39951.6, 91529.5, 2169.16};
			position[] = {5536.43, 2507.53, 0.76};
			fov = 0.48;
			date[] = {1998, 10, 1, 10, 0};
			aperture = 48;
		};
		
		class bridge1 {
			target[] = {-98080.1, -9722.99, 4387.23};
			position[] = {1092.16, 2282.79, 0.65};
			fov = 0.465;
			date[] = {3000, 12, 1, 12, 0};
			aperture = -1;
		};
		
		class swamp1 {
			target[] = {253.13, 102112, -5170.21};
			position[] = {3937.14, 2293.03, 0.95};
			fov = 0.465;
			date[] = {3000, 12, 1, 12, 0};
			aperture = -1;
		};
		
		class dawnforest1 {
			target[] = {67424.8, -77935.3, -4371.46};
			position[] = {13138.3, 5925.63, 1.43};
			fov = 0.432;
			date[] = {1998, 12, 9, 7, 33};
			aperture = 8;
		};
		
		class duskwoods1 {
			target[] = {-86017.7, -24673.7, 3691.64};
			position[] = {9043.75, 6172.72, 0.85};
			fov = 0.48;
			date[] = {3000, 12, 1, 16, 4};
			aperture = 12;
		};
		
		class duskforest1 {
			target[] = {-87264.3, -39427.2, -949.61};
			position[] = {2601.03, 4421.0, 0.81};
			fov = 0.461;
			date[] = {3000, 12, 2, 15, 54};
			aperture = 18;
		};
		
		class bridgeday1 {
			target[] = {37100.3, -90998.6, 2357.26};
			position[] = {1094.1, 2264.52, 0.83};
			fov = 0.478;
			date[] = {3000, 12, 1, 9, 20};
			aperture = 40;
		};
		
		class gasstop1 {
			target[] = {18893.2, 100360, 8800.12};
			position[] = {1124.42, 2364.92, 0.57};
			fov = 0.462;
			date[] = {2013, 6, 25, 19, 0};
			aperture = 20.0;
			overcast = 0.4;
			humidity = 0.5;
		};
	};
	
	class sampleMap {
		class default {
			target[] = {60497.8, -79032.6, -39.78};
			position[] = {2887.08, 2704.82, 1.23};
			fov = 0.491;
			date[] = {3000, 12, 1, 7, 27};
			aperture = 18;
		};
	};
};
