// config.bin - 12:06:45 05/22/17, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class empty {};
};
class DefaultAction;	// External class reference

class CfgVehicles {
	class InventoryBase;	// External class reference
	
	class PlantBase : InventoryBase {
		scope = private;
		storageCategory = 2;
		lootCategory = "Crafted";
		storeVariables[] = {"soil", "plantSlot", "cropsCount", "state", "currentStage", "isInfested", "infestationChance", "infestationScript"};
		
		class UserActions {
			class RemovePlant : DefaultAction {
				displayNameDefault = "Remove plant";
				displayName = "Remove plant";
				showWindow = 1;
				onlyForPlayer = 1;
				condition = "(this getVariable 'state' == PLANT_IS_GROWING or this getVariable 'state' == PLANT_IS_DRY)  and  !(this getVariable 'state' == PLANT_IS_DRY and itemInHands _person isKindOf 'BottleBase')";
				radius = 4;
				position = "action";
				statement = "[_person, this] spawn fnc_harvestPlant";
			};
			
			class HarvestCrops : DefaultAction {
				displayNameDefault = "Collect crops and plant";
				displayName = "Collect crops and plant";
				showWindow = 1;
				onlyForPlayer = 1;
				condition = "this getVariable 'state' == PLANT_IS_MATURE";
				radius = 4;
				position = "action";
				statement = "[_person, this] spawn fnc_harvestCropsAndPlant";
			};
			
			class HarvestSpoiledCrops : DefaultAction {
				displayNameDefault = "Collect spoiled crops and plant";
				displayName = "Collect spoiled crops and plant";
				showWindow = 1;
				onlyForPlayer = 1;
				condition = "this getVariable 'state' == PLANT_IS_SPOILED";
				radius = 4;
				position = "action";
				statement = "[_person, this] spawn fnc_harvestCropsAndPlant";
			};
			
			class WaterThePlant : DefaultAction {
				displayNameDefault = "Water the plant";
				displayName = "Water the plant";
				showWindow = 1;
				priority = 1;
				onlyForPlayer = 1;
				condition = "(itemInHands _person) isKindOf 'BottleBase'  and  this getVariable 'state' == PLANT_IS_DRY";
				radius = 4;
				position = "action";
				statement = "[_person, this] call fnc_waterPlant";
			};
			
			class DisinfectThePlant : DefaultAction {
				displayNameDefault = "Disinfect the plant";
				displayName = "Disinfect the plant";
				showWindow = 1;
				priority = 1;
				onlyForPlayer = 1;
				condition = "[this, _person] call fnc_isGardeningSpray";
				radius = 3;
				position = "action";
				statement = "[_person, this] call fnc_stopInfestation";
			};
		};
		hiddenSelections[] = {"infestedParts"};
		hiddenSelectionsTextures[] = {""};
		hiddenSelectionsMaterials[] = {""};
		
		class AnimationSources {
			class pile_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class pile_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_01_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_02_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_03 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_03_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_04 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_04_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_05 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_05_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_06 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_06_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class stake {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
		};
	};
	
	class DiggedSoil : InventoryBase {
		scope = public;
		model = "DZ\plants2\farming\soil_cultivated.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {};
		hiddenSelectionsMaterials[] = {};
		storageCategory = 2;
		lootCategory = "Crafted";
		
		class camo {
			sound = "";
			texture = "DZ\plants2\farming\data\soil_cultivated_limed_CO.paa";
			material = "DZ\plants2\farming\data\soil_cultivated_limed.rvmat ";
		};
		storeVariables[] = {"soil", "slot"};
		
		class UserActions {
			class DigPlot {
				displayNameDefault = "Prepare slot for planting";
				displayName = "Prepare slot for planting";
				priority = 1;
				radius = 2;
				showWindow = 1;
				hideOnUse = 0;
				position = "action";
				onlyForPlayer = 1;
				condition = "(itemInHands _person) call fnc_isFarmingTool && _person getVariable ['isUsingSomething',0] == 0";
				statement = "[this getVariable 'soil', (itemInHands _person), _person] spawn player_digGreenhouse;";
			};
			
			class PlantSeed : DefaultAction {
				displayNameDefault = "Plant a seed here";
				displayName = "Plant a seed here";
				onlyForPlayer = 1;
				priority = 1;
				radius = 4;
				showWindow = 1;
				hideOnUse = 1;
				position = "action";
				condition = "(itemInHands _person) isKindOf 'SeedItemBase'";
				statement = "[this getVariable 'soil', itemInHands _person, _person, this getVariable 'slot'] spawn player_digGreenhouse;";
			};
			
			class PlantPotato : DefaultAction {
				displayNameDefault = "Plant a potato here";
				displayName = "Plant a potato here";
				onlyForPlayer = 1;
				priority = 1;
				radius = 4;
				showWindow = 1;
				hideOnUse = 1;
				position = "action";
				condition = "((itemInHands _person) isKindOf 'Fruit_Potato')  and  ((itemInHands _person) getVariable 'food_stage' select 0 == 'Raw')";
				statement = "[this getVariable 'soil', itemInHands _person, _person, this getVariable 'slot'] spawn player_digGreenhouse;";
			};
			
			class FertilizeSoil : DefaultAction {
				displayNameDefault = "Fertilize this slot";
				displayName = "Fertilize this slot";
				onlyForPlayer = 1;
				priority = 1;
				radius = 4;
				showWindow = 1;
				hideOnUse = 1;
				position = "action";
				condition = "(typeOf (itemInHands _person)) call fnc_isFertilizer";
				statement = "[this getVariable 'soil', itemInHands _person, _person, this getVariable 'slot'] spawn player_digGreenhouse;";
			};
		};
	};
	
	class GardenPlot : InventoryBase {
		scope = public;
		model = "DZ\plants2\farming\garden_plot.p3d";
		storageCategory = 2;
		lootCategory = "Crafted";
		hiddenSelections[] = {"slotDigged_01", "slotDigged_02", "slotDigged_03", "slotDigged_04", "slotDigged_05", "slotDigged_06", "slotDigged_07", "slotDigged_08", "slotDigged_09", "slotDigged_10", "slotDigged_11"};
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\soil_cultivated_co.paa", "dz\plants2\farming\data\soil_cultivated_limed_CO.paa", "dz\plants2\farming\data\soil_cultivated_compost_CO.paa"};
		hiddenSelectionsMaterials[] = {};
		storeVariables[] = {"config", "baseFertility"};
		
		class AnimationSources {
			class slotDigged_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_03 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_04 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_05 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_06 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_07 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_08 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_09 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_10 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_11 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
		};
	};
	
	class Plant_Tomato : PlantBase {
		scope = public;
		model = "DZ\plants2\farming\tomato_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\tomato_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\tomato_plant.rvmat"};
	};
	
	class Plant_Pepper : PlantBase {
		scope = public;
		model = "DZ\plants2\farming\pepper_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\pepper_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\pepper_plant.rvmat"};
	};
	
	class Plant_Potato : PlantBase {
		scope = public;
		model = "DZ\plants2\farming\potato_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\potato_plant_co.paa", "dz\plants2\farming\data\potato_plant_nohq.paa", "dz\plants2\farming\data\potato_plant_smdi.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\potato_plant.rvmat"};
	};
	
	class Plant_Pumpkin : PlantBase {
		scope = public;
		model = "DZ\plants2\farming\pumpkin_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\pumpkin_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\pumpkin_plant.rvmat"};
	};
	
	class Plant_Zucchini : PlantBase {
		scope = public;
		model = "DZ\plants2\farming\zucchini_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\zucchini_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\zucchini_plant.rvmat"};
	};
	
	class Plant_Cannabis : PlantBase {
		scope = public;
		model = "DZ\plants2\farming\Cannabis_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\Cannabis_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\Cannabis_plant.rvmat"};
	};
	class HouseNoDestruct;	// External class reference
	class EN5C_Inventory_Base;	// External class reference
	
	class EN5C_PlantBase : HouseNoDestruct {
		storageCategory = 2;
		lootCategory = "Crafted";
		InteractActions[] = {1006, 1005};
		hiddenSelections[] = {"infestedParts"};
		hiddenSelectionsTextures[] = {""};
		hiddenSelectionsMaterials[] = {""};
		
		class AnimationSources {
			class pile_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class pile_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_01_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_02_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_03 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_03_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_04 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_04_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_05 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_05_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_06 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class plantStage_06_crops {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class stake {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
		};
	};
	
	class EN5C_GardenPlot : EN5C_Inventory_Base {
		scope = public;
		model = "DZ\plants2\farming\garden_plot.p3d";
		storageCategory = 2;
		lootCategory = "Crafted";
		hiddenSelections[] = {"slotDigged_01", "slotDigged_02", "slotDigged_03", "slotDigged_04", "slotDigged_05", "slotDigged_06", "slotDigged_07", "slotDigged_08", "slotDigged_09", "slotDigged_10", "slotDigged_11"};
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\soil_cultivated_co.paa", "dz\plants2\farming\data\soil_cultivated_limed_CO.paa", "dz\plants2\farming\data\soil_cultivated_compost_CO.paa"};
		hiddenSelectionsMaterials[] = {};
		
		class AnimationSources {
			class slotDigged_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_03 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_04 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_05 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_06 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_07 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_08 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_09 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_10 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_11 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
		};
	};
	
	class EN5C_Greenhouse : EN5C_Inventory_Base {
		scope = public;
		model = "\DZ\plants2\farming\Greenhouse.p3d";
		hiddenSelections[] = {"slotDigged_01", "slotDigged_02", "slotDigged_03", "slotDigged_04", "slotDigged_05", "slotDigged_06", "slotDigged_07", "slotDigged_08", "slotDigged_09", "slotDigged_10", "slotDigged_11"};
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\soil_cultivated_co.paa", "dz\plants2\farming\data\soil_cultivated_limed_CO.paa", "dz\plants2\farming\data\soil_cultivated_compost_CO.paa"};
		hiddenSelectionsMaterials[] = {};
		
		class AnimationSources {
			class slotDigged_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_03 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_04 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_05 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_06 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_07 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_08 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_09 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_10 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_11 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
		};
	};
	
	class EN5C_Plant_Tomato : EN5C_PlantBase {
		scope = public;
		model = "DZ\plants2\farming\tomato_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\tomato_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\tomato_plant.rvmat"};
		
		class Horticulture {
			GrowthStagesCount = 6;
			CropsCount = 7;
			CropsType = "EN5C_Tomato";
		};
	};
	
	class EN5C_Plant_Pepper : EN5C_PlantBase {
		scope = public;
		model = "DZ\plants2\farming\pepper_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\pepper_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\pepper_plant.rvmat"};
		
		class Horticulture {
			GrowthStagesCount = 6;
			CropsCount = 3;
			CropsType = "EN5C_GreenBellPepper";
		};
	};
	
	class EN5C_Plant_Potato : EN5C_PlantBase {
		scope = public;
		model = "DZ\plants2\farming\potato_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\potato_plant_co.paa", "dz\plants2\farming\data\potato_plant_nohq.paa", "dz\plants2\farming\data\potato_plant_smdi.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\potato_plant.rvmat"};
		
		class Horticulture {
			GrowthStagesCount = 6;
			CropsCount = 3;
			CropsType = "EN5C_Potato";
		};
	};
	
	class EN5C_Plant_Pumpkin : EN5C_PlantBase {
		scope = public;
		model = "DZ\plants2\farming\pumpkin_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\pumpkin_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\pumpkin_plant.rvmat"};
		
		class Horticulture {
			GrowthStagesCount = 7;
			CropsCount = 2;
			CropsType = "EN5C_Pumpkin";
		};
	};
	
	class EN5C_Plant_Zucchini : EN5C_PlantBase {
		scope = public;
		model = "DZ\plants2\farming\zucchini_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\zucchini_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\zucchini_plant.rvmat"};
		
		class Horticulture {
			GrowthStagesCount = 7;
			CropsCount = 2;
			CropsType = "EN5C_Zucchini";
		};
	};
	
	class EN5C_Plant_Cannabis : EN5C_PlantBase {
		scope = public;
		model = "DZ\plants2\farming\Cannabis_plant.p3d";
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\Cannabis_plant_co.paa"};
		hiddenSelectionsMaterials[] = {"dz\plants2\farming\data\Cannabis_plant.rvmat"};
		
		class Horticulture {
			GrowthStagesCount = 6;
			CropsCount = 7;
			CropsType = "EN5C_Cannabis";
		};
	};
};
