// config.bin - 11:58:30 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_Ind_Shed_02 {
		units[] = {"Land_Ind_Shed_02_main", "Land_Ind_Shed_02_end"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Ind_Shed_02_main : HouseNoDestruct {
		model = "dz\buildings2\Ind_Shed_02\Ind_Shed_02_main.p3d";
	};
	
	class Land_Ind_Shed_02_end : HouseNoDestruct {
		model = "dz\buildings2\Ind_Shed_02\Ind_Shed_02_end.p3d";
	};
};
