// config.bin - 12:08:16 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class HouseWithFireplace : HouseNoDestruct {
		class UserActions {
			class PlaceFireplace {
				displayNameDefault = "Place fireplace";
				displayName = "Place fireplace";
				onlyForPlayer = "false";
				condition = "[9, _person, []] call fireplace_action_condition";
				statement = "[9, _person, [this, 'fireplace_point', 'fireplace_smoke']] call fireplace_manageActions";
				component = "fireplace_action";
			};
		};
	};
};

class CfgPatches {
	class DZ_Structures_Houses {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures", "DZ_Structures_Furniture"};
	};
};
