// config.bin - 12:11:36 05/22/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Misc {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures", "DZ_Structures_Furniture"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_BusStop : HouseNoDestruct {
		model = "\dz\structures\Misc\misc_BusStop\BusStop.p3d";
	};
	
	class Land_BusStop_Village : HouseNoDestruct {
		model = "\dz\structures\Misc\misc_BusStop\busStop_village.p3d";
	};
	
	class Land_Misc_FeedShack : HouseNoDestruct {
		model = "\dz\structures\Misc\Misc_FeedShack\Misc_FeedShack.p3d";
	};
	
	class Land_Misc_Scaffolding : HouseNoDestruct {
		model = "\dz\structures\Misc\Misc_Scaffolding\Misc_Scaffolding.p3d";
	};
	
	class Land_Misc_GContainer_Big : HouseNoDestruct {
		model = "\dz\structures\Misc\Misc_GContainer_Big\Misc_GContainer_Big.p3d";
	};
	
	class Land_Misc_Greenhouse : HouseNoDestruct {
		model = "\dz\structures\Misc\Misc_Greenhouse\Misc_Greenhouse.p3d";
		hiddenSelections[] = {"slotDigged_01", "slotDigged_02", "slotDigged_03", "slotDigged_04", "slotDigged_05", "slotDigged_06", "slotDigged_07", "slotDigged_08", "slotDigged_09", "slotDigged_10", "slotDigged_11"};
		hiddenSelectionsTextures[] = {"dz\plants2\farming\data\soil_cultivated_co.paa", "dz\plants2\farming\data\soil_cultivated_limed_CO.paa", "dz\plants2\farming\data\soil_cultivated_compost_CO.paa"};
		hiddenSelectionsMaterials[] = {};
		
		class AnimationSources {
			class slotDigged_01 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_02 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_03 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_04 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_05 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_06 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_07 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_08 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_09 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_10 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
			
			class slotDigged_11 {
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};
		};
	};
	
	class Land_Misc_WellPump : HouseNoDestruct {
		displayName = "";
		model = "\dz\structures\Misc\Misc_WellPump\Misc_WellPump.p3d";
		storeVariables[] = {"quantity", "modifiers", "liquidType"};
		synchronizedVariables[] = {"quantity", 1, "liquidType", 1};
		
		class AnimationSources {
			class Arm {
				source = "user";
				initPhase = 0;
				animPeriod = 0.8;
			};
		};
	};
	
	class Land_Misc_DeerStand : HouseNoDestruct {
		model = "\dz\structures\Misc\Misc_DeerStand\misc_deerstand.p3d";
		displayName = $STR_MISC_DEERSTAND;
		ladders[] = {{"start1", "end1"}};
		icon = "\dz\structures\Misc\Misc_DeerStand\data\icon\icon_deerstand_ca.paa";
		mapSize = 3;
	};
	
	class Grave : HouseNoDestruct {
		icon = "dz\structures\Data\Icons\i_grave_CA.paa";
		mapSize = 2;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		armor = 20;
	};
	
	class Land_Church_tomb_1 : Grave {
		model = "\dz\structures\Misc\church\Church_tomb_1.p3d";
		displayName = $STR_DN_CHURCH_TOMB1;
	};
	
	class Land_Church_tomb_2 : Grave {
		model = "\dz\structures\Misc\church\Church_tomb_2.p3d";
		displayName = $STR_DN_CHURCH_TOMB2;
	};
	
	class Land_Church_tomb_3 : Grave {
		model = "\dz\structures\Misc\church\Church_tomb_3.p3d";
		displayName = $STR_DN_CHURCH_TOMB3;
	};
	
	class Misc_Amplion_Conc : HouseNoDestruct {
		displayName = "Amplion on concrete pole";
		model = "\dz\structures\Misc\Misc_Amplion\misc_amplion_conc.p3d";
		simulation = "pasreceiver";
		range = 50;
		gain = 2.0;
	};
	
	class Misc_Amplion_Wood : HouseNoDestruct {
		displayName = "Amplion on wooden pole";
		model = "\dz\structures\Misc\Misc_Amplion\misc_amplion_wood.p3d";
		simulation = "pasreceiver";
		range = 50;
		gain = 2.0;
	};
	
	class Land_misc_amplion_conc : Misc_Amplion_Conc {};
	
	class Land_misc_amplion_wood : Misc_Amplion_Wood {};
};
