// config.bin - 12:07:45 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Abandoned_Ship {
		units[] = {"abandoned_ship_FrontA", "abandoned_ship_FrontB", "abandoned_ship_BackA", "abandoned_ship_BackB", "abandoned_ship_Castle"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Abandoned_Ship_FrontA : HouseNoDestruct {
		model = "DZ\structures\Abandoned_ship\abandoned_ship_FrontA.p3d";
		featureSize = 50;
		ladders[] = {{"start1", "end1"}, {"start2", "end2"}};
	};
	
	class Land_Abandoned_Ship_FrontB : HouseNoDestruct {
		model = "DZ\structures\Abandoned_ship\abandoned_ship_FrontB.p3d";
		ladders[] = {{"start1", "end1"}};
	};
	
	class Land_Abandoned_Ship_BackA : HouseNoDestruct {
		model = "DZ\structures\Abandoned_ship\abandoned_ship_BackA.p3d";
		featureSize = 50;
		ladders[] = {{"start1", "end1"}};
	};
	
	class Land_Abandoned_Ship_BackB : HouseNoDestruct {
		model = "DZ\structures\Abandoned_ship\abandoned_ship_BackB.p3d";
		featureSize = 50;
		ladders[] = {{"start1", "end1"}, {"start2", "end2"}, {"start3", "end3"}, {"start4", "end4"}, {"start5", "end5"}, {"start6", "end6"}};
	};
	
	class Land_Abandoned_Ship_Castle : HouseNoDestruct {
		model = "DZ\structures\Abandoned_ship\abandoned_ship_Castle.p3d";
		featureSize = 50;
		ladders[] = {{"start1", "end1"}, {"start2", "end2"}};
	};
};
