// config.bin - 12:07:30 05/22/17, generated in 0.06 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Sounds_Arma2 {
		units[] = {"Sound_Owl", "Sound_Stream", "Sound_Frog", "Sound_Frogs", "Sound_Alarm", "Sound_Alarm2", "Sound_Fire", "Sound_BirdSinging", "Sound_Crickets1", "Sound_Crickets2", "Sound_Crickets3", "Sound_Crickets4", "Sound_Chicken", "Sound_Cock", "Sound_Cow", "Sound_Crow", "Sound_Wolf", "Sound_Dog", "Sound_BadDog", "Sound_SorrowDog", "Sound_LittleDog", "Sound_Music", "Sound_Factory01", "Sound_Factory02", "Sound_Factory03", "Sound_Factory04", "Sound_Factory05", "Sound_Factory06", "Sound_Factory07", "Sound_Factory08", "Sound_Factory09", "Sound_Factory10", "Sound_Factory11", "Sound_Factory12", "Sound_Factory13", "Sound_Factory14", "Sound_Factory15", "Sound_Factory16", "Sound_Factory17", "Sound_Factory18", "Sound_Flies"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class CfgRadio {};

class CfgWhistleSound {
	sound[] = {"dz\sounds\arma2\characters\noises\damage\wheesper1", 0.6, 1};
	downTime = 0.2;
	silentTime = 3;
	upTime = 4;
};

class CfgSounds {
	class Explosion1 {
		name = $STR_CFG_SOUNDS_EXPLOSION1;
		sound[] = {"\dz\weapons\arma2\Data\Sound\Explosion_Small_02", db0, 1.0};
		titles[] = {};
	};
	
	class Explosion2 {
		name = $STR_CFG_SOUNDS_EXPLOSION2;
		sound[] = {"\dz\weapons\arma2\Data\Sound\explosion_mega_02_building", db0, 1.0};
		titles[] = {};
	};
	
	class Fountain {
		name = $STR_CFG_SOUNDS_FOUNTAIN;
		sound[] = {"\dz\sounds\arma2\sfx\stream", 0.1, 1.0};
		titles[] = {};
	};
	
	class Fire {
		name = $STR_CFG_SOUNDS_FIRE;
		sound[] = {"\dz\sounds\arma2\sfx\fire", db-10, 1.0};
		titles[] = {};
	};
	
	class fanfare {
		name = $STR_CFG_SOUNDS_FANFARE;
		sound[] = {"\dz\sounds\arma2\sfx\fanfare", db0, 1.0};
		titles[] = {};
	};
	
	class Doors {
		name = "$STR_DN_Sounds_Doors";
		sound[] = {"dz\sounds\arma2\Vehicles\Tracked\M1A1\ext\ext-m1-door-1", 0.562341, 1.0};
		titles[] = {};
	};
	
	class Counter {
		name = "$STR_disp_arcsens_countdown";
		sound[] = {"\dz\sounds\arma2\sfx\counter", 0.1, 1.0};
		titles[] = {};
	};
};

class CfgSFX {
	access = ReadAndCreate;
	seagull[] = {"\dz\sounds\arma2\animals\gulls1", 0.1, 1, 100, 1, 0.2, 1, 5};
	
	class Preview {
		speech[] = {"DZ\sounds\mod\zombie\attack_0.ogg", 1.0, 1.0};
		effect[] = {"dz\sounds\arma2\weapons\rifles\m16_single1.wss", 1.0, 1.0};
		music[] = {"dz\sounds\mod\gore\fracture_0.wss", 1.0, 1.0};
	};
	
	class Church {
		smallBell[] = {"\dz\Buildings\sound\bell1", 1.0, 1};
		largeBell[] = {"\dz\Buildings\sound\bell2", 3.16228, 1};
	};
	
	class CA_AK {
		sounds[] = {"sound1", "sound2"};
		name = $STR_CFG_SFX_CA_AK;
		sound1[] = {"\dz\weapons\arma2\Data\Sound\AK74_2", 0.316228, 1, 500, 0.5, 0, 2, 5};
		sound2[] = {"\dz\weapons\arma2\Data\Sound\ak74_2burst", 0.316228, 1, 500, 0.4, 0, 1, 10};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 20};
	};
	
	class CA_M16 {
		sounds[] = {"sound1", "sound2"};
		name = $STR_CFG_SFX_CA_M16;
		sound1[] = {"\dz\weapons\arma2\Data\Sound\M16_2_SS", 0.316228, 1, 500, 0.5, 0, 2, 5};
		sound2[] = {"\dz\weapons\arma2\Data\Sound\M16_2_BS", 0.316228, 1, 500, 0.4, 0, 1, 10};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 20};
	};
	
	class DestrHouse {
		sounds[] = {"DestrHouse1"};
		name = "$STR_CFG_SFX_DestrHouse";
		DestrHouse1[] = {"\dz\BUILDINGS\sound\building2_destroy", 3.16228, 1, 150, 1, 60, 120, 240};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 20};
	};
	
	class Fire {
		sounds[] = {"fire1"};
		name = $STR_CFG_SFX_FIRE;
		fire1[] = {"\dz\sounds\arma2\sfx\fire", 0.0562341, 1, 20, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 20};
	};
	
	class CA_Expl1 {
		sounds[] = {"sound1"};
		name = $STR_CFG_SFX_CA_EXPL1;
		sound1[] = {"\dz\weapons\arma2\Data\Sound\explosion_large1", 10.0, 1, 700, 0.5, 0, 2, 5};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 30};
	};
	
	class hedgesparrow {
		sounds[] = {"sing1", "sing2", "sing3", "sing4", "sing5"};
		name = $STR_CFG_SFX_HEDGESPARROW;
		sing1[] = {"\dz\sounds\arma2\animals\hedspar1", 0.0177828, 1, 60, 0.1, 0, 0, 0};
		sing2[] = {"\dz\sounds\arma2\animals\hedspar2", 0.0177828, 1, 60, 0.2, 0, 0, 0};
		sing3[] = {"\dz\sounds\arma2\animals\hedspar3", 0.0177828, 1, 60, 0.1, 0, 0, 0};
		sing4[] = {"\dz\sounds\arma2\animals\hedspar4", 0.0177828, 1, 60, 0.2, 0, 0, 0};
		sing5[] = {"\dz\sounds\arma2\animals\hedspar5", 0.0177828, 1, 60, 0.3, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 80};
	};
	
	class skylark {
		sounds[] = {"sing1", "sing2", "sing3", "sing4", "sing5", "sing6", "sing7"};
		name = $STR_CFG_SFX_SKYLARK;
		sing1[] = {"\dz\sounds\arma2\animals\skylark7", 0.0177828, 1, 60, 0.1, 0.2, 0.4, 1};
		sing2[] = {"\dz\sounds\arma2\animals\skylark6", 0.0177828, 1, 60, 0.2, 0.2, 0.3, 1};
		sing3[] = {"\dz\sounds\arma2\animals\skylark5", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 1.2};
		sing4[] = {"\dz\sounds\arma2\animals\skylark4", 0.0177828, 1, 60, 0.2, 0.1, 0.2, 1.2};
		sing5[] = {"\dz\sounds\arma2\animals\skylark3", 0.0177828, 1, 60, 0.1, 0.3, 0.4, 0.75};
		sing6[] = {"\dz\sounds\arma2\animals\skylark2", 0.0177828, 1, 60, 0.1, 0.2, 0.4, 0.8};
		sing7[] = {"\dz\sounds\arma2\animals\skylark1", 0.0177828, 1, 60, 0.1, 0.1, 0.5, 0.8};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 40};
	};
	
	class forestlark {
		sounds[] = {"sing1", "sing2", "sing3", "sing4", "sing5", "sing6"};
		name = $STR_CFG_SFX_FORESTLARK;
		sing1[] = {"\dz\sounds\arma2\animals\f_lark1", 0.0177828, 1, 60, 0.1, 0.0, 0.1, 0.2};
		sing2[] = {"\dz\sounds\arma2\animals\f_lark2", 0.0177828, 1, 60, 0.1, 0.0, 0.1, 0.2};
		sing3[] = {"\dz\sounds\arma2\animals\f_lark3", 0.0177828, 1, 60, 0.1, 0.0, 0.1, 0.2};
		sing4[] = {"\dz\sounds\arma2\animals\f_lark4", 0.0177828, 1, 60, 0.1, 0.0, 0.1, 0.2};
		sing5[] = {"\dz\sounds\arma2\animals\f_lark5", 0.0177828, 1, 60, 0.2, 0.0, 0.1, 0.2};
		sing6[] = {"\dz\sounds\arma2\animals\f_lark6", 0.0177828, 1, 60, 0.2, 0.0, 0.1, 0.2};
		sing7[] = {"\dz\sounds\arma2\animals\f_lark7", 0.0177828, 1, 60, 0.2, 0.0, 0.1, 0.2};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 40};
	};
	
	class nightingale {
		sounds[] = {"sing1", "sing2", "sing3", "sing4", "sing5", "sing6", "sing7"};
		name = $STR_CFG_SFX_NIGHTINGALE;
		sing1[] = {"\dz\sounds\arma2\animals\n_gale1", 0.0177828, 1, 60, 0.2, 0.1, 0.2, 0.3};
		sing2[] = {"\dz\sounds\arma2\animals\n_gale2", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 0.3};
		sing3[] = {"\dz\sounds\arma2\animals\n_gale3", 0.0177828, 1, 60, 0.2, 0.1, 0.2, 0.3};
		sing4[] = {"\dz\sounds\arma2\animals\n_gale4", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 0.3};
		sing5[] = {"\dz\sounds\arma2\animals\n_gale5", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 0.3};
		sing6[] = {"\dz\sounds\arma2\animals\n_gale6", 0.0177828, 1, 60, 0.2, 0.1, 0.2, 0.3};
		sing7[] = {"\dz\sounds\arma2\animals\n_gale7", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 0.3};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 40};
	};
	
	class jay {
		sounds[] = {"sing1", "sing2", "sing3", "sing4"};
		name = $STR_CFG_SFX_JAY;
		sing1[] = {"\dz\sounds\arma2\animals\jay1", 0.0177828, 1, 60, 0.2, 0.2, 0.4, 1};
		sing2[] = {"\dz\sounds\arma2\animals\jay2", 0.0177828, 1, 60, 0.2, 0.2, 0.3, 1};
		sing3[] = {"\dz\sounds\arma2\animals\jay3", 0.0177828, 1, 60, 0.2, 0.1, 0.2, 1.2};
		sing4[] = {"\dz\sounds\arma2\animals\jay4", 0.0177828, 1, 60, 0.2, 0.1, 0.2, 1.2};
		empty[] = {"", 0, 0, 0, 0, 8, 20, 40};
	};
	
	class owl {
		sounds[] = {"sing1", "sing2"};
		name = $STR_CFG_SFX_OWL;
		sing1[] = {"\dz\sounds\arma2\animals\owl2_1", 0.0177828, 1, 60, 0.2, 0.0, 0.5, 1};
		sing2[] = {"\dz\sounds\arma2\animals\owl2_2", 0.0177828, 1, 60, 0.2, 0.0, 0.5, 1};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 40};
	};
	
	class crow2 {
		sounds[] = {"sing1", "sing2", "sing3", "sing4", "sing5", "sing6"};
		name = $STR_CFG_SFX_CROW2;
		sing1[] = {"\dz\sounds\arma2\animals\crow2_1", 0.0177828, 1, 60, 0.1, 0.2, 0.4, 1};
		sing2[] = {"\dz\sounds\arma2\animals\crow2_2", 0.0177828, 1, 60, 0.1, 0.2, 0.3, 1};
		sing3[] = {"\dz\sounds\arma2\animals\crow2_3", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 1.2};
		sing4[] = {"\dz\sounds\arma2\animals\crow2_4", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 1.2};
		sing5[] = {"\dz\sounds\arma2\animals\crow2_5", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 1.2};
		sing6[] = {"\dz\sounds\arma2\animals\crow2_6", 0.0177828, 1, 60, 0.1, 0.1, 0.2, 1.2};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 50};
	};
	
	class frog2 {
		sounds[] = {"sing1", "sing2", "sing3"};
		name = $STR_CFG_SFX_FROG2;
		sing1[] = {"\dz\sounds\arma2\animals\frog2_1", 0.0177828, 1, 60, 0.3, 0.0, 0.1, 0.2};
		sing2[] = {"\dz\sounds\arma2\animals\frog2_2", 0.0177828, 1, 60, 0.3, 0.0, 0.1, 0.2};
		sing3[] = {"\dz\sounds\arma2\animals\frog2_3", 0.0177828, 1, 60, 0.3, 0.0, 0.1, 0.2};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 40};
	};
	
	class SeagullSfx {
		sounds[] = {"seagull1", "Seagull2", "Seagull3", "Seagull4", "Seagull5"};
		name = $STR_CFG_SFX_SEAGULL;
		seagull1[] = {"\dz\sounds\arma2\animals\gulls1", 0.0177828, 1, 60, 0.15, 0.1, 0.5, 5};
		seagull2[] = {"\dz\sounds\arma2\animals\gulls2", 0.0177828, 1, 60, 0.2, 0.1, 0.5, 5};
		seagull3[] = {"\dz\sounds\arma2\animals\gulls3", 0.0177828, 1, 60, 0.15, 0.1, 0.5, 5};
		seagull4[] = {"\dz\sounds\arma2\animals\gulls4", 0.0177828, 1, 60, 0.24, 0.1, 0.5, 5};
		seagull5[] = {"\dz\sounds\arma2\animals\gulls5", 0.0177828, 1, 60, 0.2, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.2, 2, 20};
	};
	
	class StreamSfx {
		sounds[] = {"Stream01"};
		name = $STR_DN_STREAM;
		Stream01[] = {"\dz\sounds\arma2\sfx\stream", 0.316228, 1, 60, 1, 1, 1, 1};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory01Sfx {
		sounds[] = {"Factory01"};
		name = $STR_DN_FACTORY01;
		Factory01[] = {"\dz\sounds\arma2\sfx\factory1", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory02Sfx {
		sounds[] = {"Factory02"};
		name = $STR_DN_FACTORY2;
		Factory02[] = {"\dz\sounds\arma2\sfx\factory2", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory03Sfx {
		sounds[] = {"Factory03"};
		name = $STR_DN_FACTORY3;
		Factory03[] = {"\dz\sounds\arma2\sfx\factory3", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory04Sfx {
		sounds[] = {"Factory04"};
		name = $STR_DN_FACTORY4;
		Factory04[] = {"\dz\sounds\arma2\sfx\factory15", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory05Sfx {
		sounds[] = {"Factory05"};
		name = $STR_DN_FACTORY5;
		Factory05[] = {"\dz\sounds\arma2\sfx\factory5", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory06Sfx {
		sounds[] = {"Factory06"};
		name = $STR_DN_FACTORY6;
		Factory06[] = {"\dz\sounds\arma2\sfx\factory6", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory07Sfx {
		sounds[] = {"Factory07"};
		name = $STR_DN_FACTORY7;
		Factory07[] = {"\dz\sounds\arma2\sfx\factory7", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory08Sfx {
		sounds[] = {"Factory08"};
		name = $STR_DN_FACTORY8;
		Factory08[] = {"\dz\sounds\arma2\sfx\factory8", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory09Sfx {
		sounds[] = {"Factory09"};
		name = $STR_DN_FACTORY9;
		Factory09[] = {"\dz\sounds\arma2\sfx\factory9", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory10Sfx {
		sounds[] = {"Factory10"};
		name = $STR_DN_FACTORY10;
		Factory10[] = {"\dz\sounds\arma2\sfx\factory10", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory11Sfx {
		sounds[] = {"Factory11"};
		name = $STR_DN_FACTORY11;
		Factory11[] = {"\dz\sounds\arma2\sfx\factory11", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory12Sfx {
		sounds[] = {"Factory12"};
		name = $STR_DN_FACTORY12;
		Factory12[] = {"\dz\sounds\arma2\sfx\factory12_gas", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory13Sfx {
		sounds[] = {"Factory13"};
		name = $STR_DN_FACTORY13;
		Factory13[] = {"\dz\sounds\arma2\sfx\factory13_gas", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory14Sfx {
		sounds[] = {"Factory14"};
		name = $STR_DN_FACTORY14;
		Factory14[] = {"\dz\sounds\arma2\sfx\factory14", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory15Sfx {
		sounds[] = {"Factory15"};
		name = $STR_DN_FACTORY15;
		Factory15[] = {"\dz\sounds\arma2\sfx\factory15", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory16Sfx {
		sounds[] = {"Factory16"};
		name = $STR_DN_FACTORY16;
		Factory16[] = {"\dz\sounds\arma2\sfx\factory16", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory17Sfx {
		sounds[] = {"Factory17"};
		name = $STR_DN_FACTORY17;
		Factory17[] = {"\dz\sounds\arma2\sfx\factory17", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Factory18Sfx {
		sounds[] = {"Factory18"};
		name = $STR_DN_FACTORY18;
		Factory18[] = {"\dz\sounds\arma2\sfx\factory18", 1.0, 1, 60, 1, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class AlarmSfx {
		sounds[] = {"Alarm"};
		name = $STR_DN_ALARM;
		Alarm[] = {"\dz\sounds\arma2\sfx\sirena", 3.16228, 1, 300, 1, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class AirAlarmSfx {
		sounds[] = {"Alarm"};
		name = $STR_DN_ALARM;
		Alarm[] = {"\dz\sounds\arma2\sfx\air_raid", 3.16228, 1, 300, 1, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class AlarmBellSfx {
		sounds[] = {"Alarmbell"};
		name = $STR_CFG_SOUNDS_ALARMBELL;
		Alarmbell[] = {"\dz\sounds\arma2\sfx\alarm_bells", 3.16228, 1, 250, 1, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class Cricket1Sfx {
		sounds[] = {"Cricket01"};
		name = $STR_DN_CRICKET1;
		Cricket01[] = {"\dz\sounds\arma2\animals\cricket01", 0.0001, 1, 25, 0.96, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 2, 60};
	};
	
	class Cricket2Sfx {
		sounds[] = {"Cricket01"};
		name = $STR_DN_CRICKET2;
		Cricket01[] = {"\dz\sounds\arma2\animals\cricket02", 0.0001, 1, 25, 0.97, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 3, 60};
	};
	
	class Cricket3Sfx {
		sounds[] = {"Cricket01"};
		name = $STR_DN_CRICKET3;
		Cricket01[] = {"\dz\sounds\arma2\animals\crickets06", 0.0177828, 1, 30, 0.98, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 6, 60};
	};
	
	class CricketSfx {
		sounds[] = {"Cricket04"};
		name = $STR_DN_CRICKET4;
		Cricket04[] = {"\dz\sounds\arma2\animals\crickets04", 0.0177828, 1, 25, 1, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 2, 8};
	};
	
	class FrogSfx {
		sounds[] = {"Frog01", "Frog02"};
		name = $STR_DN_FROG;
		Frog01[] = {"\dz\sounds\arma2\animals\frog1_1", 0.017378, 1, 35, 0.8, 0.0, 0.0, 0.0};
		Frog02[] = {"\dz\sounds\arma2\animals\frog1_2", 0.0177828, 1, 35, 0.1, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0.1, 0.5, 12};
	};
	
	class FrogsSfx {
		sounds[] = {"Frog01"};
		name = $STR_DN_FROGS;
		Frog01[] = {"\dz\sounds\arma2\animals\frogs", 0.0177828, 1, 30, 1, 0.0, 0.0, 0.0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
	
	class OwlSfx {
		sounds[] = {"Owl1", "Owl2"};
		name = $STR_DN_OWL;
		Owl1[] = {"\dz\sounds\arma2\animals\owl1_1", 0.0177828, 1, 50, 0.6, 0.1, 0.5, 5};
		Owl2[] = {"\dz\sounds\arma2\animals\owl1_2", 0.0177828, 1, 50, 0.2, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.5, 2, 12};
	};
	
	class CowSfx {
		sounds[] = {"moo1", "moo2"};
		name = $STR_DN_COW;
		moo1[] = {"\dz\sounds\arma2\animals\cow_moo01", 0.0177828, 1, 50, 0.4, 0.1, 0.5, 5};
		moo2[] = {"\dz\sounds\arma2\animals\cow_moo02", 0.0177828, 1, 50, 0.4, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.1, 0.5, 2};
	};
	
	class WolfSfx {
		sounds[] = {"wolf1", "wolf2", "wolf3"};
		name = $STR_DN_WOLF;
		wolf1[] = {"\dz\sounds\arma2\animals\wolf1", 0.0177828, 1, 50, 0.3, 0.1, 0.5, 5};
		wolf2[] = {"\dz\sounds\arma2\animals\wolf2", 0.0177828, 1, 50, 0.3, 0.1, 0.5, 5};
		wolf3[] = {"\dz\sounds\arma2\animals\wolf3", 0.0177828, 1, 50, 0.3, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.5, 4, 50};
	};
	
	class CrowSfx {
		sounds[] = {"crow1", "crow2", "crow3"};
		name = $STR_DN_CROW;
		crow1[] = {"\dz\sounds\arma2\animals\crow1_1", 0.0177828, 1, 45, 0.2, 0.1, 0.5, 5};
		crow2[] = {"\dz\sounds\arma2\animals\crow1_2", 0.0177828, 1, 45, 0.2, 0.1, 0.5, 5};
		crow3[] = {"\dz\sounds\arma2\animals\crow1_3", 0.0177828, 1, 45, 0.2, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 2, 10, 30};
	};
	
	class DogSfx {
		sounds[] = {"dog1", "dog2", "dog3"};
		name = $STR_DN_DOG;
		dog1[] = {"\dz\sounds\arma2\animals\dog_bark03", 0.01, 1, 45, 0.3, 0.1, 0.5, 5};
		dog2[] = {"\dz\sounds\arma2\animals\dog_bark04", 0.01, 1, 50, 0.3, 0.1, 0.5, 5};
		dog3[] = {"\dz\sounds\arma2\animals\dog_bark04", 0.01, 1, 45, 0.2, 0.1, 0.5, 5};
		sorrowdog2[] = {"\dz\sounds\arma2\animals\dog_bark05", 0.01, 1, 50, 0.2, 0.1, 0.5, 5};
		sorrowdog3[] = {"\dz\sounds\arma2\animals\dog_yelp02", 0.00562341, 1, 55, 0.2, 0.1, 0.5, 5};
		sorrowdog4[] = {"\dz\sounds\arma2\animals\dog_yelp03", 0.00316228, 1, 45, 0.2, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.2, 3, 8};
	};
	
	class SorrowDogSfx {
		sounds[] = {"sorrowdog3", "sorrowdog4"};
		name = $STR_DN_SORROW_DOG;
		sorrowdog3[] = {"\dz\sounds\arma2\animals\dog_yelp02", 0.00562341, 1, 55, 0.2, 0.1, 0.5, 5};
		sorrowdog4[] = {"\dz\sounds\arma2\animals\dog_yelp03", 0.00316228, 1, 45, 0.2, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.2, 3, 8};
	};
	
	class BadDogSfx {
		sounds[] = {"baddog1", "baddog2", "baddog3"};
		name = $STR_DN_BAD_DOG;
		baddog1[] = {"\dz\sounds\arma2\animals\dog_bark04", 0.0177828, 1, 45, 0.3, 0.1, 0.5, 5};
		baddog2[] = {"\dz\sounds\arma2\animals\dog_bark05", 0.0177828, 1, 45, 0.3, 0.1, 0.5, 5};
		baddog3[] = {"\dz\sounds\arma2\animals\dog_maul01", 0.0177828, 1, 50, 0.3, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.1, 2, 5};
	};
	
	class LittleDogSfx {
		sounds[] = {"littledog1"};
		name = $STR_DN_LITTLE_DOG;
		littledog1[] = {"\dz\sounds\arma2\animals\dog_bark04", 0.00177828, 1, 25, 0.8, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 0.2, 3, 8};
	};
	
	class BirdSingingSfx {
		sounds[] = {"sing1", "sing1a", "sing2", "sing2a", "sing3", "sing4", "sing5", "sing6", "sing7", "sing8", "sing9"};
		name = $STR_DN_BIRDSING;
		sing1[] = {"\dz\sounds\arma2\animals\birdsing01", 0.0177828, 1, 45, 0.1, 0.2, 0.4, 1};
		sing1a[] = {"\dz\sounds\arma2\animals\birdsing01", 0.0177828, 1, 45, 0.08, 0.2, 0.3, 1};
		sing2[] = {"\dz\sounds\arma2\animals\birdsing02", 0.0177828, 1, 50, 0.1, 0.1, 0.2, 1.2};
		sing2a[] = {"\dz\sounds\arma2\animals\birdsing02", 0.0177828, 1, 50, 0.08, 0.1, 0.2, 1.2};
		sing3[] = {"\dz\sounds\arma2\animals\birdsing03", 0.0177828, 1, 55, 0.08, 0.3, 0.4, 0.75};
		sing4[] = {"\dz\sounds\arma2\animals\birdsing04", 0.0177828, 1, 55, 0.08, 0.2, 0.4, 0.8};
		sing5[] = {"\dz\sounds\arma2\animals\birdsing05", 0.0177828, 1, 55, 0.08, 0.1, 0.5, 0.8};
		sing6[] = {"\dz\sounds\arma2\animals\birdsing06", 0.0177828, 1, 60, 0.08, 0.1, 0.3, 0.8};
		sing7[] = {"\dz\sounds\arma2\animals\birdsing07", 0.0177828, 1, 60, 0.08, 0.1, 0.6, 0.8};
		sing8[] = {"\dz\sounds\arma2\animals\birdsing08", 0.0177828, 1, 65, 0.08, 0.1, 0.6, 0.8};
		sing9[] = {"\dz\sounds\arma2\animals\birdsing09", 0.0177828, 1, 65, 0.08, 0.1, 0.6, 0.8};
		empty[] = {"", 0, 0, 0, 0, 1, 5, 80};
	};
	
	class CockSfx {
		sounds[] = {"cock"};
		name = $STR_DN_COCK;
		cock[] = {"\dz\sounds\arma2\animals\cock", 0.01, 1, 35, 0.5, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 1, 30, 90};
	};
	
	class ChickenSfx {
		sounds[] = {"chicken1", "chicken2"};
		name = $STR_DN_CHICKEN;
		chicken1[] = {"\dz\sounds\arma2\animals\chicken01", 0.0177828, 1, 45, 0.3, 0.1, 0.5, 5};
		chicken2[] = {"\dz\sounds\arma2\animals\chicken02", 0.0177828, 1, 50, 0.3, 0.1, 0.5, 5};
		empty[] = {"", 0, 0, 0, 0, 1, 20, 60};
	};
	
	class FliesSfx {
		sounds[] = {"Flies1", "Flies2"};
		name = "Flies";
		Flies1[] = {"\dz\sounds\arma2\animals\flies", 0.0177828, 1, 60, 0.5, 0, 0, 0};
		Flies2[] = {"\dz\sounds\arma2\animals\flies2", 0.0177828, 1, 60, 0.5, 0, 0, 0};
		empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
};

class CfgEnvSounds {
	class Default {
		name = $STR_CFG_ENVSOUNDS_DEFAULT;
		sound[] = {$DEFAULT$, 0, 1};
		soundNight[] = {$DEFAULT$, 0, 1};
	};
	
	class Rain {
		name = $STR_DN_RAIN;
		sound[] = {"\dz\sounds\arma2\Ambient\rain\rain_hard1", db-15, 1};
		soundNight[] = {"\dz\sounds\arma2\Ambient\rain\rain_hard1", 0.177828, 1};
	};
	
	class Sea {
		name = $STR_DN_SEA;
		sound[] = {"\dz\sounds\arma2\Enviroment\wave_break_01", db-37, 1};
		soundNight[] = {"\dz\sounds\arma2\Enviroment\wave_break_02", 0.0177828, 1};
	};
	
	class WindForestHigh {
		name = $STR_DN_WIND;
		sound[] = {"dz\sounds\arma2\Ambient\forest\wind-forest-1", 0.0398107, 1};
		volume = "forest*(windy factor[0,1])*(0.1+(hills factor[0,1])*0.9)-(night*0.25)";
	};
	
	class WindNoForestHigh {
		name = $STR_DN_WIND;
		sound[] = {"dz\sounds\arma2\Ambient\forest\wind-global-2", 0.0398107, 1};
		volume = "(1-forest)*(windy factor[0,1])*(0.1+(hills factor[0,1])*0.9)-(night*0.25)";
	};
	
	class Forest {
		name = $STR_DN_WIND;
		sound[] = {"dz\sounds\arma2\Ambient\forest\forest-day-2", 0.0398107, 1};
		volume = "forest*(1-night)";
		randSamp11[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-9bird", 0.1, 1, 30, 0.14, 5, 8, 10};
		randSamp10[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-12datel", 0.1, 30, 0.125, 10, 20, 40};
		randSamp0[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-5bird", 0.125893, 1, 30, 0.13, 4, 8, 12};
		randSamp1[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-6bird", 0.125893, 1, 30, 0.125, 4, 8, 12};
		randSamp2[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-7bird", 0.125893, 1, 30, 0.125, 4, 8, 12};
		randSamp3[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-8bird", 0.125893, 1, 30, 0.1, 4, 8, 12};
		randSamp8[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-10bird-flapping", 0.1, 1, 30, 0.04, 10, 20, 40};
		randSamp9[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-11holub-flapping", 0.1, 1, 30, 0.04, 10, 20, 40};
		randSamp4[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-1", 0.1, 1, 30, 0.025, 4, 8, 10};
		randSamp5[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-2", 0.1, 1, 30, 0.025, 4, 8, 10};
		randSamp6[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-3", 0.1, 1, 30, 0.025, 4, 8, 10};
		randSamp7[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-4", 0.1, 1, 30, 0.025, 4, 8, 10};
		random[] = {"randSamp11", "randSamp10", "randSamp0", "randSamp1", "randSamp2", "randSamp3", "randSamp8", "randSamp9", "randSamp4", "randSamp5", "randSamp6", "randSamp7"};
	};
	
	class ForestNight {
		name = $STR_DN_WIND;
		sound[] = {"dz\sounds\arma2\Ambient\forest\forest-night-1", db-25, 1};
		volume = "forest*night";
		randSamp1[] = {"dz\sounds\arma2\Ambient\forest\forest-night-sfx-1", 0.1, 1 25, 0.15, 8, 15, 20};
		randSamp2[] = {"dz\sounds\arma2\Ambient\forest\forest-night-sfx-2", 0.1, 1, 25, 0.15, 8, 15, 20, 30};
		randSamp3[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-10bird-flapping", 0.1, 1 25, 0.15, 15, 30, 40};
		randSamp4[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-11holub-flapping", 0.1, 1 25, 0.15, 15, 30, 40};
		randSamp5[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-1", 0.0562341, 1, 25, 0.1, 8, 15, 20};
		randSamp6[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-2", 0.0562341, 1, 25, 0.1, 8, 10, 20};
		randSamp7[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-3", 0.0562341, 1, 25, 0.1, 8, 10, 20};
		randSamp8[] = {"dz\sounds\arma2\Ambient\forest\forest-sfx-4", 0.0562341, 1, 25, 0.1, 8, 10, 20};
		random[] = {"randSamp1", "randSamp2", "randSamp3", "randSamp4", "randSamp5", "randSamp6", "randSamp7", "randSamp8"};
	};
	
	class Houses {
		name = $STR_DN_WIND;
		sound[] = {"dz\sounds\arma2\Ambient\houses\house-1", db-40, 1};
		volume = "(houses-0.75)*4";
		randSamp11[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-07", 0.177828, 1, 25, 0.077, 10, 25, 40};
		randSamp10[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-08", 0.177828, 1, 25, 0.077, 10, 25, 40};
		randSamp0[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-09", 0.177828, 1, 25, 0.077, 10, 25, 40};
		randSamp1[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-04", 0.177828, 1, 25, 0.077, 10, 35, 60};
		randSamp2[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-05", 0.177828, 1, 25, 0.077, 10, 25, 40};
		randSamp3[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-12", 0.177828, 1, 25, 0.077, 10, 25, 40};
		randSamp8[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-07", 0.177828, 1, 25, 0.077, 10, 55, 80};
		randSamp9[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-08", 0.177828, 1, 25, 0.077, 20, 30, 40};
		randSamp4[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-09", 0.177828, 1, 25, 0.077, 10, 25, 40};
		randSamp5[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-08", 0.177828, 1, 25, 0.077, 10, 75, 100};
		randSamp6[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-04", 0.177828, 1, 25, 0.077, 10, 25, 70};
		randSamp7[] = {"dz\sounds\arma2\Ambient\houses\houses-sfx-12", 0.177828, 1, 25, 0.077, 10, 25, 40};
		random[] = {"randSamp11", "randSamp10", "randSamp0", "randSamp1", "randSamp2", "randSamp3", "randSamp8", "randSamp9", "randSamp4", "randSamp5", "randSamp6", "randSamp7"};
	};
	
	class Meadows {
		name = $STR_DN_MEADOWS;
		sound[] = {"\dz\sounds\arma2\Ambient\meadows\wind-meadow-2", db-30, 1};
		volume = "(1-forest)*(1-houses)*(1-night)*(1-sea)";
		randSamp1[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_01", 0.1, 1 25, 0.15, 8, 15, 20};
		randSamp2[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_02", 0.1, 1, 25, 0.15, 8, 15, 20};
		randSamp3[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_03", 0.1, 1 25, 0.15, 15, 30, 40};
		randSamp4[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_04_crickets", 0.01, 1, 25, 0.15, 15, 30, 40};
		randSamp5[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_05_crickets", 0.00562341, 1, 25, 0.1, 8, 15, 20};
		randSamp6[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_06", 0.01, 1, 25, 0.1, 8, 10, 20};
		random[] = {"randSamp1", "randSamp2", "randSamp3", "randSamp4", "randSamp5", "randSamp6"};
	};
	
	class MeadowsNight {
		name = $STR_DN_MEADOWS;
		sound[] = {"\dz\sounds\arma2\Ambient\meadows\wind-meadow-2", 0.0177828, 1};
		volume = "(1-forest)*(1-houses)*night*(1-sea)";
		randSamp1[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_01", 0.1, 1 25, 0.15, 8, 15, 20};
		randSamp2[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_02", 0.1, 1, 25, 0.15, 8, 15, 20};
		randSamp3[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_03", 0.1, 1 25, 0.15, 15, 30, 40};
		randSamp4[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_04_crickets", 0.01, 1, 25, 0.15, 15, 30, 40};
		randSamp5[] = {"dz\sounds\arma2\Ambient\meadows\meadow_sfx_05_crickets", 0.00562341, 1, 25, 0.1, 8, 15, 20};
		random[] = {"randSamp1", "randSamp2", "randSamp3", "randSamp4", "randSamp5"};
	};
};

class CfgVehicles {
	class Sound {
		scope = private;
		side = -1;
		animated = false;
		vehicleClass = "Sounds";
		icon = "\dz\sounds\arma2\data\icon_soundsource_ca";
		mapSize = 10;
		faction = "dz_None";
	};
	
	class Sound_Owl : Sound {
		scope = public;
		sound = "OwlSfx";
		displayName = $STR_DN_OWL;
	};
	
	class Sound_Stream : Sound {
		scope = public;
		sound = "StreamSfx";
		displayName = $STR_DN_STREAM;
	};
	
	class Sound_Frog : Sound {
		scope = public;
		sound = "FrogSfx";
		displayName = $STR_DN_FROG;
	};
	
	class Sound_Frogs : Sound {
		scope = public;
		sound = "FrogsSfx";
		displayName = $STR_DN_FROGS;
	};
	
	class Sound_Alarm : Sound {
		scope = public;
		sound = "AlarmSfx";
		displayName = $STR_DN_ALARM;
	};
	
	class Sound_Alarm2 : Sound {
		scope = public;
		sound = "AirAlarmSfx";
		displayName = "$STR_DN_Sound_Alarm2";
	};
	
	class Sound_Factory01 : Sound {
		scope = protected;
		sound = "Factory01Sfx";
		displayName = "Factory01";
	};
	
	class Sound_Factory02 : Sound {
		scope = protected;
		sound = "Factory02Sfx";
		displayName = "Factory02";
	};
	
	class Sound_Factory03 : Sound {
		scope = protected;
		sound = "Factory03Sfx";
		displayName = "Factory03";
	};
	
	class Sound_Factory04 : Sound {
		scope = protected;
		sound = "Factory04Sfx";
		displayName = "Factory04";
	};
	
	class Sound_Factory05 : Sound {
		scope = protected;
		sound = "Factory05Sfx";
		displayName = "Factory05";
	};
	
	class Sound_Factory06 : Sound {
		scope = protected;
		sound = "Factory06Sfx";
		displayName = "Factory06";
	};
	
	class Sound_Factory07 : Sound {
		scope = protected;
		sound = "Factory07Sfx";
		displayName = "Factory07";
	};
	
	class Sound_Factory08 : Sound {
		scope = protected;
		sound = "Factory08Sfx";
		displayName = "Factory08";
	};
	
	class Sound_Factory09 : Sound {
		scope = protected;
		sound = "Factory09Sfx";
		displayName = "Factory09";
	};
	
	class Sound_Factory10 : Sound {
		scope = protected;
		sound = "Factory10Sfx";
		displayName = "Factory10";
	};
	
	class Sound_Factory11 : Sound {
		scope = protected;
		sound = "Factory11Sfx";
		displayName = "Factory11";
	};
	
	class Sound_Factory12 : Sound {
		scope = protected;
		sound = "Factory12Sfx";
		displayName = "Factory12";
	};
	
	class Sound_Factory13 : Sound {
		scope = protected;
		sound = "Factory13Sfx";
		displayName = "Factory13";
	};
	
	class Sound_Factory14 : Sound {
		scope = protected;
		sound = "Factory14Sfx";
		displayName = "Factory14";
	};
	
	class Sound_Factory15 : Sound {
		scope = protected;
		sound = "Factory15Sfx";
		displayName = "Factory15";
	};
	
	class Sound_Factory16 : Sound {
		scope = protected;
		sound = "Factory16Sfx";
		displayName = "Factory16";
	};
	
	class Sound_Factory17 : Sound {
		scope = protected;
		sound = "Factory17Sfx";
		displayName = "Factory17";
	};
	
	class Sound_Factory18 : Sound {
		scope = protected;
		sound = "Factory18Sfx";
		displayName = "Factory18";
	};
	
	class Sound_Fire : Sound {
		scope = public;
		sound = "fire";
		displayName = "$STR_DN_Sound_Fire";
	};
	
	class Sound_BirdSinging : Sound {
		scope = public;
		sound = "BirdSingingSfx";
		displayName = $STR_DN_BIRDSING;
	};
	
	class Sound_Crickets1 : Sound {
		scope = public;
		sound = "Cricket1Sfx";
		displayName = $STR_DN_CRICKET1;
	};
	
	class Sound_Crickets2 : Sound {
		scope = public;
		sound = "Cricket2Sfx";
		displayName = $STR_DN_CRICKET2;
	};
	
	class Sound_Crickets3 : Sound {
		scope = public;
		sound = "Cricket3Sfx";
		displayName = $STR_DN_CRICKET3;
	};
	
	class Sound_Crickets4 : Sound {
		scope = public;
		sound = "CricketSfx";
		displayName = $STR_DN_CRICKET4;
	};
	
	class Sound_Chicken : Sound {
		scope = public;
		sound = "ChickenSfx";
		displayName = $STR_DN_CHICKEN;
	};
	
	class Sound_Cock : Sound {
		scope = public;
		sound = "CockSfx";
		displayName = $STR_DN_SND_COCK;
	};
	
	class Sound_Cow : Sound {
		scope = public;
		sound = "CowSfx";
		displayName = $STR_DN_SND_COW;
	};
	
	class Sound_Crow : Sound {
		scope = public;
		sound = "CrowSfx";
		displayName = $STR_DN_CROW;
	};
	
	class Sound_Wolf : Sound {
		scope = public;
		sound = "WolfSfx";
		displayName = $STR_DN_WOLF;
	};
	
	class Sound_Dog : Sound {
		scope = public;
		sound = "DogSfx";
		displayName = $STR_DN_DOG;
	};
	
	class Sound_BadDog : Sound {
		scope = public;
		sound = "BadDogSfx";
		displayName = $STR_DN_BAD_DOG;
	};
	
	class Sound_SorrowDog : Sound {
		scope = public;
		sound = "SorrowDogSfx";
		displayName = $STR_DN_SORROW_DOG;
	};
	
	class Sound_LittleDog : Sound {
		scope = public;
		sound = "LittleDogSfx";
		displayName = $STR_DN_LITTLE_DOG;
	};
	
	class Sound_Music : Sound {
		scope = public;
		sound = "FunMusicSfx";
		displayName = $STR_DN_MUSIC;
	};
	
	class Sound_Flies : Sound {
		scope = protected;
		sound = "FliesSfx";
		displayName = "Flies";
	};
};
