// config.bin - 11:58:06 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_Rail_House_01 {
		units[] = {"Land_Rail_House_01"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class Land_Rail_House_01 : House {
		armor = 300;
		model = "dz\buildings2\Rail_House_01\Rail_House_01.p3d";
		
		class HitPoints {
			class Hit1 {
				armor = 0.1;
				material = -1;
				name = "dam 1";
				visual = "damT1";
				passThrough = false;
				convexComponent = "dam 1";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
			
			class Hit2 {
				armor = 1e-005;
				material = -1;
				name = "dam 2";
				visual = "damT2";
				passThrough = false;
				convexComponent = "dam 2";
				
				class DestructionEffects {
					class Dust {
						simulation = "particles";
						type = "HousePartDust";
						position = "";
						intensity = 1;
						interval = 1;
						lifeTime = 0.01;
					};
					
					class Dust2 : Dust {
						type = "HousePartDustLong";
					};
					
					class Walls : Dust {
						type = "HousePartWall";
					};
				};
			};
		};
		
		class Damage {
			tex[] = {};
			mat[] = {};
		};
	};
};
