// config.bin - 12:01:20 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Roads2_Bridge {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Roads2"};
	};
};

class CfgNonAIVehicles {
	class Land_Bridge_stone_asf2_25 {
		model = "\dz\roads2\bridge\Bridge_stone_asf2_25.p3d";
		simulation = "road";
		armor = 50;
		
		class Destruction {
			animations[] = {{"dz\roads2\bridge\data\anim\bridge_stone_asf2.rtm", 0.2, 3}};
		};
	};
};
