// config.bin - 12:13:49 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Wall {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Wall_CBrk_5_D : HouseNoDestruct {
		model = "\dz\structures\Wall\Wall_CBrk_5_D";
	};
	
	class Land_Wall_CGry_5_D : HouseNoDestruct {
		model = "\dz\structures\Wall\Wall_CGry_5_D";
	};
	
	class Land_Wall_Gate_Kolchoz : HouseNoDestruct {
		model = "\dz\structures\Wall\Wall_Gate_Kolchoz";
	};
	
	class Land_Wall_Gate_Ind1_L : HouseNoDestruct {
		armor = 50;
		model = "\dz\structures\Wall\Wall_Gate_Ind1_L.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0;
				armor = 0.2;
				soundOpen = "doorFenceMetalOpen";
				soundClose = "doorFenceMetalClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Wall_Gate_Ind1_R : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Ind1_R";
	};
	
	class Land_Wall_Gate_Ind2A_L : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Ind2A_L";
	};
	
	class Land_Wall_Gate_Ind2A_R : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Ind2A_R";
	};
	
	class Land_Wall_Gate_Ind2B_L : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Ind2B_L";
	};
	
	class Land_Wall_Gate_Ind2B_R : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Ind2B_R";
	};
	
	class Land_Wall_Gate_Ind2Rail_L : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Ind2Rail_L";
	};
	
	class Land_Wall_Gate_Ind2Rail_R : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Ind2Rail_R";
	};
	
	class Land_Wall_Gate_Village : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Village";
	};
	
	class Land_Wall_Gate_Wood1 : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Wall_Gate_Wood1";
	};
	
	class Land_Gate_wood2_5 : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Gate_wood2_5";
	};
	
	class Land_Gate_Wood1_5 : Land_Wall_Gate_Ind1_L {
		model = "\dz\structures\Wall\Gate_Wood1_5";
	};
};

class CfgNonAIVehicles {
	class StaticObject;	// External class reference
	
	class WallWithHole : StaticObject {};
	
	class Static_Wall_WoodF_5 : WallWithHole {
		model = "\dz\structures\Wall\Wall_WoodF_5";
	};
	
	class Static_Wall_WoodF_5_2 : WallWithHole {
		model = "\dz\structures\Wall\Wall_WoodF_5_2";
	};
	
	class Static_Wall_IndCnc_4_D : WallWithHole {
		model = "\dz\structures\Wall\Wall_IndCnc_4_D";
	};
};
