// config.bin - 12:12:15 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Nav_Pier {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Structures", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class Thing;	// External class reference
	class HouseNoDestruct;	// External class reference
	
	class Land_nav_pier_m_2 : HouseNoDestruct {
		model = "\dz\structures\Nav_Pier\nav_pier_m_2.p3d";
		armor = 800;
	};
	
	class land_nav_pier_c : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c";
	};
	
	class land_nav_pier_c2 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c2";
	};
	
	class land_nav_pier_c2_end : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c2_end";
	};
	
	class land_nav_pier_c_270 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c_270";
	};
	
	class land_nav_pier_c_90 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c_90";
	};
	
	class land_nav_pier_c_big : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c_big";
	};
	
	class land_nav_pier_C_L10 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_C_L10";
	};
	
	class land_nav_pier_C_R : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_C_R";
	};
	
	class land_nav_pier_C_R10 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_C_R10";
	};
	
	class land_nav_pier_C_R30 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_C_R30";
	};
	
	class land_nav_pier_c_t15 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c_t15";
	};
	
	class land_nav_pier_c_t20 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_c_t20";
	};
	
	class land_nav_pier_F_17 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_F_17";
	};
	
	class land_nav_pier_F_23 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_F_23";
	};
	
	class land_nav_pier_m_1 : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_m_1";
	};
	
	class land_nav_pier_m_end : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_m_end";
	};
	
	class land_nav_pier_M_fuel : Land_nav_pier_m_2 {
		model = "\dz\structures\Nav_Pier\nav_pier_M_fuel";
	};
	
	class Land_nav_pier_pneu : Thing {
		scope = public;
		animated = false;
		model = "\DZ\structures\Nav_Pier\nav_pier_pneu.p3d";
		destrType = "DestructNo";
	};
	
	class Land_nav_pier_uvaz : Land_nav_pier_pneu {
		model = "\DZ\structures\Nav_Pier\nav_pier_uvaz.p3d";
	};
};
