// config.bin - 21:04:49 06/19/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_Shed_wooden {
		units[] = {"Land_Shed_wooden"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Buildings2"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Shed_wooden : HouseNoDestruct {
		scope = public;
		displayName = "Shed Wooden";
		model = "dz\buildings2\Shed_wooden\Shed_wooden.p3d";
		animated = true;
		vehicleClass = "Misc";
		mapSize = 2;
		editorCategory = "DayZ";
		editorSubcategory = "DayZ_Buildings";
		
		class AnimationSources {
			class doors1 {
				source = "user";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
			};
		};
		
		class UserActions {
			class OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "doors1_action";
				radius = 3;
				onlyForPlayer = 0;
				condition = "((this animationSourcePhase 'doors1') < 0.5)";
				statement = "(this animateSource ['doors1', 1])";
			};
			
			class CloseDoors_1 : OpenDoors_1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "((this animationSourcePhase 'doors1') >= 0.5)";
				statement = "(this animateSource ['doors1', 0])";
			};
		};
	};
};
