// config.bin - 12:00:15 05/22/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_A_GENERALSTORE_01 {
		units[] = {"Land_A_GeneralStore_01", "Land_A_GeneralStore_01a"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_A_GeneralStore_01 : HouseNoDestruct {
		armor = 400;
		animated = true;
		model = "dz\buildings2\A_GeneralStore_01\A_GeneralStore_01.p3d";
		
		class Doors {
			class DoorsTwin1 {
				displayName = "door Twin1";
				component = "DoorsTwin1";
				soundPos = "doorsTwin1_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.6;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin2 {
				displayName = "door Twin2";
				component = "DoorsTwin2";
				soundPos = "doorsTwin2_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin3 {
				displayName = "door Twin3";
				component = "DoorsTwin3";
				soundPos = "doorsTwin3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin4 {
				displayName = "door Twin4";
				component = "DoorsTwin4";
				soundPos = "doorsTwin4_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
			
			class DoorsTwin5 {
				displayName = "door Twin5";
				component = "DoorsTwin5";
				soundPos = "doorsTwin5_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.2;
				armor = 0.2;
				soundOpen = "doorMetalTwinOpen";
				soundClose = "doorMetalTwinClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_A_GeneralStore_01a : Land_A_GeneralStore_01 {
		armor = 300;
		model = "dz\buildings2\A_GeneralStore_01\A_GeneralStore_01a.p3d";
	};
};
