// config.bin - 12:11:54 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Misc_Misc_NewsStand {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures_Misc"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	class HouseNoDestruct;	// External class reference
	
	class Land_Misc_NewsStand : HouseNoDestruct {
		model = "DZ\structures\Misc\Misc_NewsStand\Misc_NewsStand.p3d";
		
		class Doors {
			class Doors1 {
				displayName = "door 1";
				component = "Doors1";
				soundPos = "doors1_action";
				animPeriod = 1;
				initPhase = 1;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
		
		class AnimationSources {
			class Shutter1 {
				source = "user";
				initPhase = 1;
				animPeriod = 0.8;
			};
			
			class Shutter2 {
				source = "user";
				initPhase = 1;
				animPeriod = 0.8;
			};
		};
		
		class UserActions {
			class Shutter1Open {
				displayName = "Open Shutter";
				displayNameDefault = "Open Shutter";
				position = "shutter1_action";
				radius = 1;
				onlyForPlayer = 0;
				condition = "this animationPhase ""shutter1"" < 0.5 && damage this < 1";
				statement = "this animate [""shutter1"",1];";
				component = "shutter1";
			};
			
			class Shutter1Close : Shutter1Open {
				displayName = "Close Shutter";
				displayNameDefault = "Close Shutter";
				condition = "this animationPhase ""shutter1"" >= 0.5 && damage this < 1";
				statement = "this animate [""shutter1"",0];";
			};
			
			class Shutter2Open : Shutter1Open {
				displayName = "Open Shutter";
				displayNameDefault = "Open Shutter";
				position = "shutter2_action";
				radius = 1;
				onlyForPlayer = 0;
				condition = "this animationPhase ""shutter2"" < 0.5 && damage this < 1";
				statement = "this animate [""shutter2"",1];";
				component = "shutter2";
			};
			
			class Shutter2Close : Shutter2Open {
				displayName = "Close Shutter";
				displayNameDefault = "Close Shutter";
				condition = "this animationPhase ""shutter2"" >= 0.5 && damage this < 1";
				statement = "this animate [""shutter2"",0];";
			};
		};
	};
};
