// config.bin - 18:27:52 06/21/17, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Misc_Misc_NewsStand {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Structures_Misc"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	class HouseNoDestruct;	// External class reference
	
	class Land_Misc_NewsStand : HouseNoDestruct {
		model = "DZ\structures\Misc\Misc_NewsStand\Misc_NewsStand.p3d";
		
		class AnimationSources {
			class Doors1 {
				source = "user";
				initPhase = 1;
				animPeriod = 1;
			};
		};
		
		class UserActions {
			class OpenDoors1 {
				displayNameDefault = $STR_DN_OUT_O_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_O_DOOR;
				position = "Doors1_action";
				radius = 2;
				onlyForPlayer = 0;
				condition = "(this animationPhase 'Doors1' >= 0.5)";
				statement = "(this animate ['Doors1', 0])";
			};
			
			class CloseDoors1 : OpenDoors1 {
				displayNameDefault = $STR_DN_OUT_C_DOOR_DEFAULT;
				displayName = $STR_DN_OUT_C_DOOR;
				condition = "(this animationPhase 'Doors1' < 0.5)";
				statement = "(this animate ['Doors1', 1])";
			};
		};
		actionBegin1 = "OpenDoors1";
		actionEnd1 = "OpenDoors1";
	};
};
