// config.bin - 12:01:38 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Signs2 {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class Land_Company3_2 : House {
		armor = 5;
		model = "\dz\signs2\Company3_2.p3d";
		
		class DestructionEffects {
			class DestroyPhase1 {
				simulation = "destroy";
				type = "DelayedDestruction";
				lifeTime = 2.5;
				position = "";
				intensity = 1;
				interval = 1;
			};
		};
	};
	
	class Land_sign_altar : Land_Company3_2 {
		model = "\dz\signs2\sign_altar.p3d";
	};
	
	class Land_Sign_Bar_RU : Land_Company3_2 {
		model = "\dz\signs2\Sign_Bar_RU.p3d";
	};
	
	class Land_Sign_BES : Land_Company3_2 {
		model = "\dz\signs2\Sign_BES.p3d";
	};
	
	class Land_SignB_Gov : Land_Company3_2 {
		model = "\dz\signs2\SignB_Gov.p3d";
	};
	
	class Land_SignB_GovPolice : Land_Company3_2 {
		model = "\dz\signs2\SignB_GovPolice.p3d";
	};
	
	class Land_SignB_GovSchool : Land_Company3_2 {
		model = "\dz\signs2\SignB_GovSchool.p3d";
	};
	
	class Land_SignB_GovSign : Land_Company3_2 {
		model = "\dz\signs2\SignB_GovSign.p3d";
	};
	
	class Land_SignB_Hotel_CZ2 : Land_Company3_2 {
		model = "\dz\signs2\SignB_Hotel_CZ2.p3d";
	};
	
	class Land_SignB_PostOffice : Land_Company3_2 {
		model = "\dz\signs2\SignB_PostOffice.p3d";
	};
	
	class Land_SignB_Pub_CZ1 : Land_Company3_2 {
		model = "\dz\signs2\SignB_Pub_CZ1.p3d";
	};
	
	class Land_SignB_Pub_CZ2 : Land_Company3_2 {
		model = "\dz\signs2\SignB_Pub_CZ2.p3d";
	};
	
	class Land_SignB_Pub_CZ3 : Land_Company3_2 {
		model = "\dz\signs2\SignB_Pub_CZ3.p3d";
	};
	
	class Land_SignB_Pub_RU1 : Land_Company3_2 {
		model = "\dz\signs2\SignB_Pub_RU1.p3d";
	};
	
	class Land_SignB_Pub_RU2 : Land_Company3_2 {
		model = "\dz\signs2\SignB_Pub_RU2.p3d";
	};
	
	class Land_SignB_Pub_RU3 : Land_Company3_2 {
		model = "\dz\signs2\SignB_Pub_RU3.p3d";
	};
};
