// config.bin - 12:01:29 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Rocks2 {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class CfgNonAIVehicles {
	class StaticObject;	// External class reference
	
	class Static_r2_boulder1 : StaticObject {};
	
	class Static_r2_boulder2 : StaticObject {};
	
	class Static_small_stone_01_f : StaticObject {};
	
	class Static_small_stone_02_f : StaticObject {};
	
	class Static_stone_small_f : StaticObject {};
	
	class Static_stone_small_w : StaticObject {};
	
	class Static_bluntstone_01 : StaticObject {};
	
	class Static_bluntstone_01_lc : StaticObject {};
	
	class Static_bluntstone_02 : StaticObject {};
	
	class Static_bluntstone_02_lc : StaticObject {};
	
	class Static_bluntstone_03 : StaticObject {};
	
	class Static_SharpStone_01 : StaticObject {};
	
	class Static_sharpstone_01_lc : StaticObject {};
	
	class Static_sharpstone_02 : StaticObject {};
	
	class Static_sharpstone_02_lc : StaticObject {};
	
	class Static_sharpstone_03 : StaticObject {};
	
	class Static_sharpstone_03_lc : StaticObject {};
};
