// config.bin - 12:11:01 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Structures_Ind_SawMill {
		units[] = {"Land_Ind_SawMill"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Buildings"};
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	
	class Land_Ind_SawMill : HouseNoDestruct {
		model = "\dz\structures\Ind_SawMill\Ind_SawMill.p3d";
		armor = 20000;
		ladders[] = {{"start", "end"}};
		
		class Doors {
			class Doors3 {
				displayName = "door 3";
				component = "Doors3";
				soundPos = "doors3_action";
				animPeriod = 1;
				initPhase = 0;
				initOpened = 0.5;
				armor = 0.2;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorWoodRattle";
			};
		};
	};
	
	class Land_Ind_IlluminantTower : HouseNoDestruct {
		displayName = $STR_MISC_ILLUMINANTTOWER;
		model = "\dz\structures\Ind_SawMill\Ind_IlluminantTower.p3d";
		icon = "\dz\misc3\Data\Icons\icomap_illuminantTower_CA.paa";
		ladders[] = {{"start", "end"}};
	};
	
	class Land_Ind_SawMillPen : HouseNoDestruct {
		model = "\dz\structures\Ind_SawMill\Ind_SawMillPen.p3d";
	};
	
	class Land_Ind_Timbers : HouseNoDestruct {
		displayName = $STR_MISC_TIMBERS;
		model = "\dz\structures\Ind_SawMill\Ind_Timbers.p3d";
		icon = "\dz\structures\Data\Icons\i_timbers_ca.paa";
		mapSize = 9;
	};
	
	class Land_Ind_BoardsPack1 : HouseNoDestruct {
		displayName = $STR_MISC_BOARDSPACK;
		model = "\dz\structures\Ind_SawMill\Ind_BoardsPack1.p3d";
		icon = "\dz\misc3\Data\Icons\icomap_BoardsPack_CA.paa";
		mapSize = 2;
	};
	
	class Land_Ind_BoardsPack2 : Land_Ind_BoardsPack1 {
		displayName = $STR_MISC_BOARDSPACK2;
		model = "\dz\structures\Ind_SawMill\Ind_BoardsPack2.p3d";
	};
};
