// config.bin - 12:00:09 05/22/17, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	DESTRUCTNO = 0,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Buildings2_A_Statue {
		units[] = {"Land_A_statue01", "Land_WW2Monument_stele"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Buildings", "DZ_Buildings2"};
	};
};

class CfgVehicles {
	class House;	// External class reference
	
	class Land_A_statue01 : House {
		armor = 500;
		model = "dz\buildings2\A_Statue\A_statue01.p3d";
	};
	
	class Land_A_statue02 : House {
		model = "dz\buildings2\A_Statue\A_statue02.p3d";
	};
	
	class Land_WW2Monument_stele : House {
		armor = 500;
		model = "dz\buildings2\A_Statue\WW2Monument_stele.p3d";
	};
};
